[oscar.award] 자동차 경주 step2 제출합니다.
next-step/java-racingcar-kakao pull request #106
Opened 2022-12-30 06:45 UTC by queueSub

안녕하세요 oscar 입니다!

리뷰해주신 내용들 + 온보딩 강의에서 배운 내용들을 나름대로 최대한 반영하여 리팩토링 진행했습니다.
물론 리팩토링 해놓고 보니 이게 맞는건가...? 하는 부분도 있긴 하지만, 앞으로 더 배워가며 개선해보도록 하겠습니다.

aiden 리뷰 잘 부탁드립니다!

2023-01-02 00:35 UTC, YooInKeun requested changes
2단계 미션 진행하시느라 고생 많으셨습니다 오스카~ 👍 
1단계 때 나눴던 이야기를 고려하고 깔끔하게 잘 반영해주셔서 감사합니다 🙇‍♂️ 
몇가지 얘기하고 싶은 내용에 대해 코멘트 남겼으니 확인해보시고 재요청 부탁드려요~!
새해 복 많이 받으시고 즐거운 월요일 보내셨으면 좋겠습니다~ 화이팅!! 🔥 🔥

2023-01-02 00:35 UTC, YooInKeun commented on src/main/java/racingcar/domain/car/RacingCar.java
> +        this("car");
"car" 의 의미와 역할을 알 수 있도록 상수로 빼주는 것은 어떨까요?

2023-01-02 00:35 UTC, YooInKeun commented on src/main/java/racingcar/domain/game/RacingGame.java
> +        this.cars = names.stream()
`stream` 을 잘 활용해주셨네요 😄

2023-01-02 00:35 UTC, YooInKeun commented on src/test/java/racingcar/RacingCarTest.java
> +    public void not_move(final int power) {
메소드명은 컨벤션에 맞게 카멜 케이스로 작성해주는 것이 좋아 보여요!

2023-01-02 00:35 UTC, YooInKeun commented on src/test/java/racingcar/RacingCarTest.java
> +        //when, then
when, then 구문을 한 번에 작성하기 보다 가독성을 위해 나누어서 작성하는 것이 좋아보여요~

ex)
```java
        //when
        car.move(() -> power);
        
        //then
        assertEquals(1, car.getPos());
```

2023-01-04 00:34 UTC, YooInKeun approved these changes
피드백 잘 반영해주셨네요~ 👍 
자동차 미션 진행하시느라 고생 많으셨습니다 오스카
이어서 로또 미션에서 봬요~ 🔥

2023-01-04 00:34 UTC, YooInKeun commented on src/main/java/racingcar/view/InputView.java
> +            validateCarName(carName);
`RacingCarName` 객체를 생성할 때도 validation 을 하는 것이 좋아 보여요~

2023-01-04 00:35 UTC, merged

2023-01-04 03:21 UTC, queueSub commented on src/main/java/racingcar/view/InputView.java
> +            validateCarName(carName);
생성시에 validation을 꼼꼼히 해야겠네요. 앞으로 잘 반영해보겠습니다!
코드리뷰 자세히 해주셔서 감사합니다! 많은 도움이 되었어요 👍🏻