refactor: MVC 패턴 적용 - View에서 Model 의존성 제거
next-step/java-racingcar-kakao pull request #36
Opened 2024-03-28 01:09 UTC by gunom

## 리뷰 요청 사항
Step1에서 MVC 패턴을 일부 사용하였기에 View에서 Model을 직접 받아 사용하는 부분만 의존성을 제거해주었습니다.
이 과정에서 List<String>을 사용하였는데, 특별히 일급 컬렉션 객체를 만드는 것이 좋을지 고민되네요.

2024-03-28 15:38 UTC, Rok93 requested changes
건모님 안녕하세요. 
1단계 미션을 머지하면서 추가로 남겨둔 코멘트들이 있는데, 이 부분이 반영이안된 것 같습니다. 🥲
코멘트들 확인해서 반영해주시고 다시 리뷰요청 부탁드립니다. 🙏

2024-03-28 15:38 UTC, Rok93 commented on src/main/java/controller/RacingGameController.java
RacingGameController가 직접 상태 값을 가지는 것이 아니라 
Controller 내부의 핸들러 메서드(= startGame) 안에서 View로부터 입력받은 값을 파싱하여 RacingGame 객체와 tryNums를 만들도록 변경이 필요할 것 같아요. 😃 (Controller의 인스턴스 변수가 아니라 핸들러 메서드의 지역 변수로 선언하고 생성한 객체들은 협력하여 자동차 경주 게임이라는 비즈니스를 수행하도록해야해요! )

아래의 글을 참고해보시면 좋을 것 같아요. 🙂
[웹 MVC 각 컴포넌트 역할](https://tecoble.techcourse.co.kr/post/2021-04-26-mvc/)

2024-03-28 15:38 UTC, Rok93 commented on src/main/java/controller/RacingGameController.java
[자바 코드 컨벤션](https://myeonguni.tistory.com/1596)에서는 아래와 같이 가이드하고있어요. 

>  if 문은 항상 중괄호를 사용한다. 다음과 같은 에러가 발생할 수 있는 상황은 피해야 한다.

setup 메서드의 두 번째 while문블록의 if문은 중괄호를 추가해줘야할 것 같아요. 👀

2024-03-28 15:38 UTC, Rok93 commented on src/main/java/controller/RacingGameController.java
또한 고민해볼부분은 입력 값이 잘못되서 다시 입력을 받는 행위를 Controller에서 처리(while문으로 처리한부분) 하셨는데, 
입력이 잘못되어서 다시 입력을 받는 것은 View의 역할이라고도 볼 수 있지 않을까요? 🤔

2024-04-01 01:30 UTC, gunom commented on src/main/java/controller/RacingGameController.java
의견 감사합니다!

2024-04-01 03:03 UTC, Rok93 requested changes
건모님 피드백 반영 잘해주셨네요. 👍
몇몇 코멘트 남겨두었으니 확인해서 반영 부탁드려요! 🙏
이해가 잘 안되는 부분이있으면 언제든지 DM 주세요.

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/view/RacingGameView.java
> +        carNames = getInput();
아래와 같이 변수를 선언과 할당을 따로하는 것이 아니라 선언하는 시점에 할당을 하도록 변경해주세요. 
```
String carNames = getinput();
```

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/controller/RacingGameController.java
>          }
View에서 아래와 같이 입력이 없는경우 재입력받는 로직이 이미 있으니 Controller에서는 이 로직이 필요없지 않을까요? 🙂

```java
        carNames = getInput();
        while (carNames.isEmpty()) {
            System.out.println("자동차 이름을 입력해주세요.");
            carNames = getInput();
        }
```

```suggestion
```

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/racing/RacingGame.java
> +    private List<String> getWinnerNames(List<Car> winner) {
메서드 파라미터로 전달되는 값이 그냥 `List<Car> cars` 라면 지금의 메서드명은 완전히 달라지지 않을까요? 
이 메서드의 메서드 파라미터로 우승자만 전달한다는 것을 보장할 수 있을까요? 🙄

단순히 `getNames` `extreactNames` 와 같은 네이밍이 조금 더 적절하지 않을까요? 😃

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/racing/RacingGame.java
> +    private int getWinnerPosition(Map<Integer, List<Car>> groupByPosition) {
사소하지만 여기도 우승자라는 표현보다는 getMaxPosition 같은 표현이 조금 더 좋다고 생각해요.  😃 (그런데 한편으로는 이 케이스는 우승자가 결국 max position일거니까... 이건 사람마다 조금 다르게 생각할 수 있을 것 같네요. 😁)

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/view/RacingGameView.java
> +            return -1;
여기서 -1을 반환하는 것이 아니라 다시 `return getInteger()` 을 한다면,   `getTryNums`에서 또 다시 -1에 케이스에 대해서 다시 입력을 받도록 할 필요가 없을 것 같네요. 🙂

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/view/RacingGameView.java
> +        positionInfos.forEach(System.out::println);
현재는 car.`display`() 메서드로 자동차의 출력 문구를 정의하고있는 것 같아요. 

MVC 패턴에 입각해서 생각해보면 만약 자동차의 출력 형태가 변경(ex. - symbol 대신 숫자로 표현)된다고 생각해볼까요? 
MVC 패턴에 입각해보면 순수하게 View의 변경이기 때문에 View 로직만 변경하면 될 것 같지만 지금의 경우에는 어디를 수정하게될까요? 😃

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/racing/RacingGame.java
>      private final MovingStrategy movingStrategy;
`movingStrategy`를  RacingGame의 인스턴스로 둘 필요가 있을지 고민해보면 좋을 것 같아요! 
`movingStrategy`가 필요한 시점에만 메서드 파라미터로 주입받는다면 불필요한 인스턴스 변수를 줄일 수 있을 것 같아요! 😃

2024-04-01 03:03 UTC, Rok93 commented on src/main/java/racing/RacingGame.java
> +    private final int tryNums;
RacingGame이 `tryNums` 인스턴스 변수가 내부에서 쓰이지 않는 것 같은데, 
현재 Controller에 `playround`에 있는 로직을 RacingGame 객체 내부로 옮겨서 도메인 로직으로 변경해보면 어떨까요? 😃

2024-04-02 01:02 UTC, gunom commented on src/main/java/controller/RacingGameController.java
>          }
수정하다가 놓쳤네요ㅎㅎ 감사합니다!

2024-04-02 01:03 UTC, gunom commented on src/main/java/view/RacingGameView.java
> +            return -1;
좋은 의견 감사합니다!

2024-04-02 01:04 UTC, gunom commented on src/main/java/racing/RacingGame.java
> +    private final int tryNums;
좋은 것 같습니다!

2024-04-02 12:27 UTC, Rok93 approved these changes
건모님 2단계 피드백 잘 반영해주셨네요. 😃
처음보다 코드가 더 많이 보기좋아진 것 같아요. 😉👍

몇몇 코멘트남겨두었는데 확인 부탁드릴게요, 
아쉽지만 이번 미션은 여기서 종료하도록하겠습니다. 😄
남은 미션도 화이팅입니다. 💪💪

2024-04-02 12:27 UTC, Rok93 commented on src/main/java/racing/CarInfo.java
> +    private final int carPosition;
사소하지만  `carInfo.name`, `carInfo.position` 이라고해도  자동차의 `이름`, `위치`인지 쉽게 파악할 수 있을 것 같아서.
prefix를 굳이 안붙여줘도 괜찮을 것 같다고 생각되네요. 😃

물론 이런 네이밍의 영역은 정해진 답이있는 것은 아니니 건모님이 네이밍하신 것처럼 중복처럼보일 수 있어도 조금 더 명확하게 짓는게 좋을 수도 있다고 생각해요. 🙂 (그냥 이렇게 생각해볼 수 있다 정도로 생각해주세요!)

2024-04-02 12:27 UTC, Rok93 commented on src/main/java/racing/RacingGame.java
>      }
아마도 playRounds 메서드에대한 테스트가 없는 이유는 이 메서드가 테스트하기가 어려웠기 때문일 것 같아요. 🤔

아래와 같이 변경했다면 테스트하기힘든 random 요소를 가진 `moveStrategy`를  비즈니스 로직 밖으로 꺼낼 수 있고 
테스트할 수 있는 코드가 됐을 것 같아요. 😃  

```suggestion
    public List<List<CarInfo>> playRounds(MoveStrategy moveStrategy) {
        List<List<CarInfo>> rounds = new ArrayList<>();
        rounds.add(getCarsPositionInfos());
        IntStream.range(0, tryNums).forEach(i -> {
            moveCars(moveStrategy);
            rounds.add(getCarsPositionInfos());
        });
        return rounds;
    }

    private void moveCars(MoveStrategy moveStrategy) {
        cars.forEach(car -> car.moveForward(moveStrategy.generateNumber()));
    }
```

2024-04-02 12:27 UTC, merged