[pluto.yun]자동차 경주 1단계 미션
next-step/java-racingcar-kakao pull request #38
Opened 2022-12-28 02:43 UTC by tkaltk123

2022-12-28 15:21 UTC, sangnyyy requested changes
안녕하세요!
플루토의 코드리뷰어로 활동하게된 광고서버개발파트의 레오입니다 :)

첫번쨰 미션 진행해주시느라 고생이 많으셨습니다!
이와 관련하여 리뷰 남겨보았으니 확인 부탁드립니다.

감사합니다 :)

2022-12-28 15:21 UTC, sangnyyy commented on src/test/java/racingcar/CarTest.java
> +    Engine engine;
Mock 대신 Fake 객체를 사용해보시는 것을 권장드려봅니다.

참고) https://jessyt.tistory.com/152

참고해보시고 적용해보시다가 잘 안되면 말씀주세요 :)

2022-12-28 15:21 UTC, sangnyyy commented on src/main/java/racingcar/Engine.java
> +    public static final Engine defaultEngine = new Engine(10);
상수는 private 으로 제한하고 싱글턴 반환 시 메서드를 통해 반환하시는 것이 어떠실까요?

2022-12-28 15:21 UTC, sangnyyy commented on src/main/java/racingcar/CarInfo.java
> +public class CarInfo {
Car 객체가 있는데 CarInfo 를 따로 만드신 이유가 있으실까요?
또한, 네이밍이 가장 어렵긴 하지만 Info, Data 등 postfix 를 갖는 모호한 네이밍은 지양하는 것이 어떠실까요?

참고) https://github.com/Yooii-Studios/Clean-Code/blob/master/Chapter%2002%20-%20%EC%9D%98%EB%AF%B8%20%EC%9E%88%EB%8A%94%20%EC%9D%B4%EB%A6%84.md

2022-12-29 07:54 UTC, tkaltk123 reviewed
문자열 덧셈기에 피드백 반영했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringAccumulator.java
> +    String content;
수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringAccumulator.java
> +    private static boolean hasSeparator(String str) {
수정했습니다 감사합니다.

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringAccumulator.java
> +            throw new RuntimeException("Invalid string.");
파싱하는 역할을 한 객체로 묶었고 거기서 상수화 했습니다. 감사합니다.

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringAccumulator.java
> +            throw new RuntimeException("Invalid string.");
수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringAccumulator.java
> +        return StringSplitter.from(separator)
DI로 변경했고 content를 입력받아 반복적으로 사용할 수 있도록 수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringAccumulator.java
> +    public boolean equalsTo(String separator, String content) {
제거했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +    List<String> separators;
수정했습니다.

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +    private StringSplitter(String separatorFormat) {
포맷을 받지 않고 구분자를 직접 받는 형태로 수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +            return;
separators를 만들지 않고 customSeparator 유무를 바로 확인하는 방식으로 수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +    private static void checkFormatValidation(String separatorFormat) {
수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +    private static boolean isInvalidFormat(String separatorFormat) {
수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +            separators.add(0, customSeparator);
수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +    public boolean contains(String separator) {
삭제했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/main/java/stringaccumulator/StringSplitter.java
> +        String splitRegex = String.join("|", separators);
수정했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/test/java/stringaccumulator/StringSplitterTest.java
> +                }).isInstanceOf(RuntimeException.class);
추가했습니다!

2022-12-29 07:54 UTC, tkaltk123 commented on src/test/java/stringaccumulator/StringSplitterTest.java
> +                assertThat(splitter.contains("")).isFalse();
테스트가 제거됐습니다. 감사합니다.

2022-12-29 08:27 UTC, sangnyyy commented
> 문자열 덧셈기에 피드백 반영했습니다!

@tkaltk123 변경사항에 대한 커밋 푸시 해주신거 맞으실까요?
커밋이 보이질 않아서요.

2022-12-29 08:51 UTC, tkaltk123 reviewed
Fake 객체를 제외한 1차과제에 대한 피드백 전부 반영했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/Car.java
> +        checkEngineExists();
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/Car.java
> +        if (engine.getPower() >= POWER_THRESHOLD) {
이동 관련 로직을 엔진으로 이관했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/CarInfo.java
> +public class CarInfo {
view에 전달하기 위해 만들었고 용도에 맞게 CarDto로 이름을 수정했습니다! 감사합니다.

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/Engine.java
> +    public static final Engine defaultEngine = new Engine(10);
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/RacingCarModel.java
> +    private final List<Car> cars;
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/RacingCarModel.java
> +    }
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/RacingCarModel.java
> +        if (getDistinctCarsCount() != cars.size()) {
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/RacingCarModel.java
> +                .map(car -> car.getCarInfo().getName())
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/RacingCarModel.java
> +    }
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/RacingCarModel.java
> +        return names;
갯수를 팩토리 메소드에서 검증하고 파싱은 컨트롤러로 이관했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/main/java/racingcar/RacingCarModel.java
> +public class RacingCarModel {
수정했습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/test/java/racingcar/CarTest.java
> +    Engine engine;
넵 적용해보겠습니다!

2022-12-29 08:51 UTC, tkaltk123 commented on src/test/java/racingcar/RacingCarModelTest.java
> +                    .isInstanceOf(RuntimeException.class);
넵 추가하겠습니다!

2022-12-29 09:18 UTC, tkaltk123 commented
헉 개인 저장소에만 푸시되고 pr에 반영이 안됐네요. 빨리 올리겠습니다!

2022-12-29 12:08 UTC, sangnyyy approved these changes
고생하셨습니다!

제가 많은 코멘트를 드렸는데 빠르고 훌륭하게 반영해주셔서 매우 놀랐습니다.
많은 도움이 되셨길 바랍니다 :)

몇가지 추가 코멘트 남겼으니 확인 부탁드리고 다음 PR 에서 반영해주시길 바랍니다.
머지하도록 하겠습니다 !! 👏👏👏

2022-12-29 12:08 UTC, sangnyyy commented on src/main/java/racingcar/Engine.java
> +    }
이 부분(검증이 어려운 부분)에 대한 Mock 에 의존하지 않고 테스트를 어떻게 진행할 지 고민해보세요 ^^

2022-12-29 12:08 UTC, sangnyyy commented on src/main/java/racingcar/RacingCarController.java
> +    private RacingCars racingCars;
사실 필드로 설정을 굳이 해야하나? 하는 생각이 들긴합니다. 
private final 을 사용할 수 있도록 연습해봅시다!

2022-12-29 12:08 UTC, sangnyyy commented on src/main/java/racingcar/RacingCars.java
> +    public List<CarDto> getWinners() {
여기도 마찬가지입니다. RacingCars 는 CarDto 보다 고수준의 객체이기 때문에 의존하면 저수준의 변경에 영향을 받아 변경에 취약한 단단하지 못한 코드가 됩니다.

2022-12-29 12:08 UTC, merged

2022-12-29 14:24 UTC, tkaltk123 reviewed
2차 PR에 피드백 반영했습니다!

2022-12-29 14:24 UTC, tkaltk123 commented on src/main/java/racingcar/Engine.java
> +    }
전략패턴을 도입하고 익명 객체를 생성하는 방식으로 테스트했습니다!