2단계 미션 제출합니다.
next-step/java-racingcar-kakao pull request #43
Opened 2024-03-28 07:42 UTC by baejunghyun36

- 역할을 추측할 수 있는 네이밍으로 수정 
- boolean -> void 수정 및 Exception 처리 
- 기본 생성자를 통한 객체 생성 x

2024-04-01 09:42 UTC, sah3122 requested changes
안녕하세요 정현님 😄 
이번 미션의 요구사항인 `domain 패키지의 객체는 view 패키지 객체에 의존하지 않도록 구현한다.`가 지켜지지 않은것 같아 수정 요청 드립니다. 
미션의 코드를 보면 Domain 객체와 View 객체가 아직 의존성을 가지고 있는것을 확인할수 있어요.  https://github.com/baejunghyun36/java-racingcar-kakao/blob/step2/src/main/java/racingcar/view/View.java 

이번 미션에서는 이와 같은 의존성의 제거가 왜 필요한지 고민하고, 제거하기 위해 노력해보세요 😄

2024-04-01 09:42 UTC, sah3122 commented on src/main/java/racingcar/model/Car.java
>      }
기본 생성자를 private 으로 막는것이 어떨까요 ? 
https://ktko.tistory.com/entry/Effective-Java-4-%EA%B0%9D%EC%B2%B4-%EC%83%9D%EC%84%B1%EC%9D%84-%EB%A7%89%EC%9D%84-%EB%95%8C%EB%8A%94-private-%EC%83%9D%EC%84%B1%EC%9E%90%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EB%9D%BC?category=753411

2024-04-01 11:01 UTC, baejunghyun36 commented on src/main/java/racingcar/model/Car.java
>      }
아 이런 방법도 있네요~ 감사합니다 :)

2024-04-02 08:22 UTC, sah3122 requested changes
남겨드린 코멘트가 모호하여 잘못 이해해주신것 같아요. 
추가로 코멘트 남겨두었는데 확인 부탁드리며 질문이 있을경우 편하게 DM 주세요 😄

2024-04-02 08:22 UTC, sah3122 commented on src/main/java/racingcar/view/View.java
> +    public static String input() {
static 함수로 변경하는것이 의존성을 제거했다고 볼수 있을까요 ?

2024-04-02 08:22 UTC, sah3122 commented on src/main/java/racingcar/view/View.java
> +    public static void displayMoveResult(List <Car> cars) {
남겨드린 코멘트의 의도가 모호했던것 같습니다. 
코멘트의 의도는 나누어진 레이어간의 의존성을 제거하여 격리를 시키는것이 목적이었습니다. 
현재 View 패키지는 여전히 Domain 객체에 대한 의존성을 가지고 있습니다. 

UI Layer, Persentation Layer까지 Domain 객체가 전달되면 어떤 문제점이 있을지 고민해보세요.

2024-04-02 08:22 UTC, sah3122 commented on src/main/java/racingcar/view/View.java
>  public class View {
클래스가 한가지 역할만 할수 있게 Input / Output View를 나누어 보는건 어떨까요 ?

2024-04-03 07:05 UTC, sah3122 commented
Slack으로 나눈 이야기를 기록차 남겨드립니다 😄 
```
코멘트에 궁금한 것이 생겨서 여쭤봅니다! 혹시 도메인 객체를 받지말고 DTO를 생성해서 전달 받아야하는걸까요?
public static String input()
-> "static 함수로 변경하는것이 의존성을 제거했다고 볼수 있을까요 ?"
그리고 이러한 코멘트도 받았는데, static으로 객체 생성없이 클래스 메서드 영역으로 바로 접근해서 수행하면 의존성이 제거되지 않나 생각했습니다..!

-> 
네넵 값 전달으 위한 DTO를 생성해보는것이 맞습니다 :slightly_smiling_face:
더불어 단순히 DTO 생성에 의미를 두기 보단, 왜 DTO를 생성하여 전달해야할지에 대해 고민해보시면 도움이 되실거에요 !

static 함수로 변경한다는것이 외적으로는 의존성이 제거 되었다고도 볼수 있어요. 이야기 주신것처럼 객체 생성을 하지 않으니깐요.
조금더 넓게 본다면 static 함수를 사용하기 위해 특정 클래스의 정보를 알아야 합니다. 이러한 경우도 의존성이 남아있다고 생각하는데 정현님의 의견은 어떠실까요 ?

->
먼저, 첫번째에 대한 답변은 도메인 객체는 데이터의 일관성과 무결성을 보장해야하는데 매개변수로 전달하면 데이터의 변형이 발생할 가능성이 있다고 생각합니다.
두번째는 의존성은 완전히 제거되지 않을 것 같습니다. 하지만 특정 클래스의 정보를 알아야 출력이 가능할거 같은데 의존성을 완전히 없애고 어떻게 print를 할 수 있는지 감이 잡히지 않아요..! 객체 생성없이 그리고 Static 말고 의존성을 완전히 제거해서 input이나 output을 뽑아내는 방법이 있을까요..?

->
이번 미션에서의 의존성 제거는 domain 객체가 외부에 노출되지 않도록 하는것 입니다 :slightly_smiling_face:
ui layer (presentation layer)까지 `도메인 객체`가 전달되는것을 DTO를 생성하여 의존을 제거하는것이 목표입니다.

도메인 객체는 데이터의 일관성과 무결성을 보장해야하는데 매개변수로 전달하면 데이터의 변형이 발생할 가능성
현재 도메인 객체가 외부로 전달되는 경우, 예를 들어 View Layer에서 car.move() 라는 메서드를 호출할수 있는 상황이 제한되어 있지 않습니다.
만약, 빈약한 도메인 객체라면 호출할 메서드가 없기 때문에 문제가 되지 않을수 있어요. 하지만 앞으로 미션을 진행하며 메시지를 던지는 구조로 변경해보세요.라는 피드백을 받으실거에요.
도메인 객체가 적절한 책임을 가지고, 필요한 역할을 할수 있는 존재가 될것이기 때문에 외부로 유출되는것을 막을수 있어야 합니다 :smile:
```

2024-04-03 07:05 UTC, sah3122 approved these changes
마지막 피드백까지 반영잘해주셨어요 👍 
자동차 경주 미션은 여기서 마무리 짓도록 할게요 🙏 
남아있는 과정들도 끝까지 화이팅 해주세요 !

2024-04-03 07:05 UTC, sah3122 commented on src/main/java/dto/CarResponse.java
> +public class CarResponse {
값전달을 위한 DTO 객체 선언 👍

2024-04-03 07:05 UTC, sah3122 commented on src/main/java/dto/CarResponse.java
> +    private final int position;
DTO의 특성에 맞게 불변객체로 선언 잘해주셨네요 👍

2024-04-03 07:05 UTC, sah3122 commented on src/main/java/racingcar/view/OutputView.java
> +import static java.util.stream.Collectors.joining;
클래스의 import 구문을 보면 어떤 패키지와 의존성을 가지고 있는지 쉽게 알수 있습니다. 
domain 패키지와의 의존성 부리 잘해주셨어요 👍

2024-04-03 07:06 UTC, merged