2단계 미션 제출합니다.
next-step/java-racingcar-kakao pull request #45
Opened 2024-03-28 08:37 UTC by KimJS0328

안녕하세요!

1단계 때 주신 피드백을 바탕으로 약간의 수정을 해보았습니다.

### 수정사항 1

여러 테스트들을 `@ParameterizedTest`를 활용하여 리팩토링 해봤습니다.
다만, 메소드 이름을 non-ascii로도 가능하다는 것을 알게되어 `@DisplayName` 대신 활용해봤습니다.
메소드 이름과 `@DisplayName` 두 곳에 두 번 적는 것보다 좀 더 깔끔하다고 느껴서 이런 접근을 사용해봤습니다.

### 수정사항 2

`CarEngine`이 `Car`가 움직이는 거리를 결정하도록 변경하였습니다. 큰 차이는 없지만 좀 더 확장이 용이하다고 생각했기 때문입니다.

`move`에서만 사용된다는 피드백에 대해서 고민해봤습니다. 비록 `move`에서만 사용하긴 하지만, `Car` 객체 각각의 움직이는 거리 혹은 움직임 여부를 결정하는 객체이기 때문에 `Car` 클래스 내부에서 관리해야 한다고 생각했습니다. 물론 현재 요구 사항에서는 `Car` 클래스 별로 별도로 관리할 이유가 크게 없긴 하지만, 확장의 용이성 관점에서 이렇게 설계해봤습니다.

### 수정사항 3

페어와 논의해본 결과, `CarEngine`의 구현체는 네트워크나 DB 등에 의존성이 생길 가능성이 있을 수 있고, 그러한 상황에서 `domain` 패키지에 있는 것은 적절치 않다고 생각했습니다. 이 역시 이후 확장을 고려하여 설계해본 결과입니다.

### 수정사항 4

`CarName`으로 검증 로직을 분리해봤습니다. 처음에는 조금 과도한 분리가 아닐까 생각했는데, 연습을 위한 과제라는 점에서 시도해봤습니다.

### 수정사항 5

일급 콜렉션 객체 관련 공유해주신 글을 읽고 반환 데이터의 불변에 대해 고민해봤습니다.
일반적으로 DTO 등을 사용하면 원본 데이터를 보호할 수 있지만, 간단한 데이터에 대해 새로운 클래스를 만들어야 하는 점이 걸렸습니다.
그래서 `Race` 객체의 `forEach` 메소드를 만들어 각 라운드 결과에 대한 임의의 동작을 콜백을 통해 수행할 수 있도록 수정해봤습니다.

감사합니다!!

2024-03-29 05:13 UTC, hyunssooo requested changes
안녕하세요. 
몇 가지 코멘트 남겼습니다. 확인 부탁드려요!

2024-03-29 05:13 UTC, hyunssooo commented on src/main/java/racing/domain/Race.java
> +            .collect(Collectors.toList());
https://github.com/next-step/java-racingcar-kakao/pull/23#discussion_r1540881155

2024-03-29 05:13 UTC, hyunssooo commented on src/test/java/racing/domain/CarFactoryTest.java
> +	void 유효한_이름들() {
tab 과 space를 함께 사용하고 있으신데 보통 space 4칸을 사용합니다. tab은 viewer 마다 다르게 보일 수 있습니다.

2024-03-29 05:13 UTC, hyunssooo commented on src/main/java/racing/domain/CarName.java
> +public class CarName {
👍 
https://tecoble.techcourse.co.kr/post/2020-06-11-value-object/
이 글이 도움이 되면 좋겠어요.

2024-03-29 05:13 UTC, hyunssooo commented on src/main/java/racing/infra/RandomCarEngine.java
>      }
테스트를 위해서 접근제어자를 protected로 선언했네요. 프로덕션 코드가 테스트를 위해 변경이 있는 것이 좋을까요? 
CarEngine 이라는 잘 만들어둔 인터페이스가 있으니 테스트용 구현체를 만들어 보는 것은 어떨까요?

2024-03-29 05:13 UTC, hyunssooo commented on src/test/java/racing/domain/RaceTest.java
>      }
`@BeforeEach` 과의 차이점은 무엇일까요? CarEngine 이 statci으로 선언될 이유가 따로 있었을까요? 

```java
    private final CarEngine brokenEngine = new RandomCarEngine() {
        @Override
        protected int generateRandomCondition() {
            return 0;
        }
    };
    private final CarEngine normalEngine = new RandomCarEngine() {
        @Override
        protected int generateRandomCondition() {
            return 9;
        }
    };
```

바로 생성해서 반복해서 사용해도 괜찮을 것 같아서요.

2024-03-29 05:13 UTC, hyunssooo commented on src/main/java/racing/domain/Race.java
>      }
오 좀 특이하네요. 이 메서드는 웹 환경으로 바뀐다면 어떻게 사용할 수 있나요?

2024-03-29 05:13 UTC, hyunssooo commented on src/main/java/racing/domain/Race.java
>      }
파일로 분리하는게 좋을 것 같아요. Predicate 는 이미 자바에서 제공하는 인터페이스이니 다른 이름으로 변경하는 것은 어떨까요?

2024-03-29 07:23 UTC, KimJS0328 commented on src/main/java/racing/domain/Race.java
> +            .collect(Collectors.toList());
혹시 `getPosition`이 `maxPosition`을 구하는데 사용되는 부분 말씀해주신 걸까요??

2024-03-29 07:24 UTC, KimJS0328 commented on src/main/java/racing/domain/CarName.java
> +public class CarName {
참고해서 수정해보겠습니당!

2024-03-29 07:38 UTC, hyunssooo commented on src/main/java/racing/domain/Race.java
> +            .collect(Collectors.toList());
아이고 제가 코드 잘못 봤네요. 죄송합니다. 🙇‍♂️
`Car#locates` 확인했습니다. 

별도로 `CarName` 이라는 클래스가 있는데 `List<String>` 를 리턴하는 이유가 있을까요?  
Car 클래스에 `Comparable` 을 구현하면 getter 없이도 구현 가능하겠네요!

2024-03-29 09:17 UTC, KimJS0328 commented on src/main/java/racing/domain/Race.java
>      }
추상적인 관점에서는 똑같이 사용할 수 있을 것 같습니다. 메소드 호출이 메시지를 전달하는 것이라는 관점에서 보면, 그냥 컨트롤러가 모델에게 `메시지를 보낼 장소`를 보내고, 모델은 메시지에 적힌 장소로 자신의 메시지를 보내는 것이기 때문입니다.

제가 Java 웹 개발 경험이 없어서 MVC 패턴이 어떻게 적용되고 지금 구조와 어떤 차이가 있는지 잘 몰라서, 정확히 어떻게 사용될 수 있는지는 잘 모르겠습니다. 혹시 한계가 있는 방법이라면 알려주시면 감사하겠습니다!

2024-03-29 09:39 UTC, hyunssooo commented on src/main/java/racing/domain/Race.java
>      }
> 가장 간단한 방법은 DTO를 사용하는 것

네 저도 DTO를 떠올릴 것 같은데요. 혹은 불변 객체를 사용할 수 도 있겠죠. 

> DTO를 사용하는 것은 이런 간단한 문제 상황에서 적절하지 않다

DTO가 여기서 적절하지 않다고 생각하신 이유는 어떤 이유일까요?? 

편하게 의견 말씀 부탁드려요!

2024-03-29 09:50 UTC, KimJS0328 commented on src/main/java/racing/domain/Race.java
>      }
간단한 문제를 위해 너무 많은 파일이 생성된다고 느꼈기 때문인 것 같습니다.

그래서 1) 이후 DTO나 VO 등을 도입해도 코드 구조에 큰 변화가 없고, 2) DTO를 사용하지 않아도 상태 변화를 막을 수 있는 방법을 생각했습니다.

그런데 이 프로젝트의 목적이 학습을 위한 것이고, 저도 다른 부분에서는 이후의 확장 등을 고려한 설계를 생각한 만큼 DTO를 도입하는 것이 더 적절하다면 이를 활용하는 것이 맞는 것 같습니다.

혹시 컨트롤러가 모델에게 데이터를 받고 이를 뷰에게 전달하는 것이 아닌, 컨트롤러가 모델에게 뷰에 대한 콜백을 던져주는 지금 방식에 어떤 한계가 있을까요??

2024-03-29 10:02 UTC, KimJS0328 commented on src/main/java/racing/domain/CarName.java
> +public class CarName {
VO에 대해 추상적으로만 이해하고 있었는데 조금 더 구체적인 상을 가질 수 있게 된 것 같습니다. 감사합니다!!

2024-03-29 10:05 UTC, KimJS0328 commented on src/main/java/racing/domain/Race.java
> +            .collect(Collectors.toList());
저는 `CarName`을 딱 검증 로직의 분리로만 생각하고 VO, 원시값 포장 등으로 생각하지는 못한 것 같습니다.

그런데 차 이름에 해당하는 모든 부분을 다 포장하면 조금 불필요하게 코드가 추가되는 부분이 너무 많아지는 것 같습니다. 물론 OOP 설계 학습 관점에서 의미 있는 것이지만,, 혹시 다음 과제에서 시도해봐도 될까요..

2024-03-29 11:01 UTC, hyunssooo commented on src/main/java/racing/domain/Race.java
>      }
필드가 늘어나면 Predicate로 받아야할 데이터가 늘어날 것 같고 다르게 응답을 내려야 한다면 분기 혹은 새로운 Predicate 같은 인터페이스가 필요할 수 도 있겠네요. 

이 미션에서 view에 이렇게 내리는걸 처음 봐서 재밌게 봤습니다. 👍

2024-03-29 11:02 UTC, hyunssooo commented on src/main/java/racing/domain/Race.java
> +            .collect(Collectors.toList());
넵 선택입니다. :) 다음 미션은 OOP 관련 미션이니 그때 시도해 보아도 좋을 것 같아요.

2024-03-29 11:54 UTC, KimJS0328 commented
수정사항입니다!!

## Indentation
인텔리제이 indentation 설정이  잘못 되어 있었습니당.. 감사합니다!!

## 테스트를 위한 코드
이후 확장성을 생각해서 도입해본 `CarEngine`에 대해서 0~9 모든 경우에 대해 테스트를 하고자 했습니다.
그런데 이를 위해 또 숫자 생성 책임을 분리하면 너무 복잡해진다고 생각해서 조금 꼼수를 썼던 것 같습니다.

최종적으로는 요구사항에 집중하고 좀더 간단한 구조를 갖는 것이 낫다고 생각하였습니다. 따라서, 움직임 여부를 결정하는 로직을 `Car`로 옮기고 `NumberGenerator` 인터페이스를 사용하는 것으로 수정하였습니다.

## 테스트 셋업
`@BeforeEach`는 각 메소드를 생성할 때마다 실행되는데, 해당 테스트에서 이전의 `CarEngine`와 현재의 `Generator` 모두 정해진 숫자를 반환할 뿐이라 딱 한번만 생성되면 된다고 생각했습니다. 그래서 테스트 클래스 생성 시 처음 실행되는 `@BeforeAll`을 선택했고, 이를 위해 각 변수를 `static`으로 지정하였습니다.

2024-03-30 15:52 UTC, hyunssooo approved these changes
안녕하세요. 
이번 step 진행하신다고 고생 많으셨습니다! 
다음 미션도 잘 진행하시길 바랄게요. 🙂

2024-03-30 15:52 UTC, merged