[marcus.min] 문자열 덧셈 계산기 & 자동차 경주 1단계
next-step/java-racingcar-kakao pull request #46
Opened 2022-12-28 06:12 UTC by ekzm8523

### 안녕하세요 웨이드!! 처음으로 리뷰 요청을 하게 되었네요 😊
### 자바 프로그래밍이 익숙치 않아 부족한 부분도 많고 코딩하면서도 계속 이게 맞나? 라는 생각을 하면서 코딩을 한 것 같아요 ㅎㅎ..
### 자바쪽의 컨벤션을 아직 잘 몰라서 따끔한 리뷰 부탁드립니다!!

2022-12-28 11:24 UTC, wade-lim requested changes
안녕하세요 마커스~ 굉장히 잘해주셔서 조금 자잘한 부분까지 의견 드리게 되네요 ㅎㅎ

자바는 많이 안 해보셨다고는 생각할 수 없을 정도로 꼼꼼하게 구현해주셨네요.

고생하셨습니다~

2022-12-28 11:24 UTC, wade-lim commented on src/main/java/racing/domain/Game.java
> +    }
[확인]
의미가 불명확한 Map 을 반환하는 대신 `cars` 를 반환하는건 어떨까요?
만약 외부에서 `Car` 상태를 조작하지 못하도록 제한하고 싶은 경우 두 가지 방법 중 하나를 사용할 수 있을 것 같습니다.
1. `CarStatus` 와 같은 차량 상태를 볼 수 있는 클래스 생성 후 반환
2. `Car` 을 상속하면서 상태를 수정할 수 있는 메소드를 제한해놓은 `ImmutableCar` 과 같은 프록시 객체로 반환
    - ex) [UnmodifiableList](https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/list/UnmodifiableList.html)

2번의 경우 `Car` 를 인터페이스로 만들어두면 `Car` 의 `cars` 가 상속되는 문제를 방지할 수 있습니다.

```java
public interface Car {
  String getName();
  // ...
}
```

```java
public class RacingCar implements Car {
  // ...
}
```

```java
public class ImmutableCar implements Car {
  private final Car car;
  // ...

  @Override
  public void move() {
    throw new UnsupportedOperationException();
  }
}
```

2022-12-28 11:24 UTC, wade-lim commented on src/main/java/racing/domain/Game.java
> +    }
[의견]
`Car` 객체를 반환하거나, 메소드명을 `decideWinnersName` 과 같이 구체적으로 변경하는건 어떨까요?

2022-12-28 11:24 UTC, wade-lim commented on src/main/java/racing/domain/Name.java
> +    private String name;
[의견]
primitive type 을 래핑해서 사용하는거 좋은 것 같습니다 :)

2022-12-28 11:24 UTC, wade-lim commented on src/test/java/calculator/StringAdderCalculatorTest.java
> +    }
[의견]
ParameterizedTest 과 테스트 관련 어노테이션들 다양하게 사용하시는거 좋은 것 같습니다 👍

2022-12-28 11:24 UTC, wade-lim commented on src/main/java/racing/domain/Cars.java
> +        return status;
[TIP]
요것도 위에 하신 것처럼 Stream API 를 이용하면 임시 변수 없이 처리할 수 있습니다.

```java
return cars.stream()
    .collect(Collectors.toMap(
        Car::getName, 
        Car::getPosition));
```

2022-12-28 12:05 UTC, ekzm8523 commented on src/main/java/calculator/domain/Prompt.java
> +public class Prompt {
현재 Prompt가 컨트롤러와 데이터 모델의 기능을 동시에 하고 있네요!!
현재 Prompt를 Interpreter로 네이밍을 변경하고 Command라는 클래스를 데이터 모델로 가져가는건 어떤가요? (너무 개발자같은 네이밍이긴 한데..)
``` Java
Calculator calculator = new Calculator();
Interpreter interpreter = new Interpreter();
Command command = interpreter.decode(scanner.readLine());
System.out.println(calculator.calculate(command);
```
요런 느낌이나
위와 같은 로직을 가져가되 calculator 내부에 interpreter를 숨기는 방식도 있을 것 같아요
``` Java
Calculator calculator = new Calculator();
System.out.println(calculator.calculate(scanner.readLine());
```

2022-12-28 12:07 UTC, ekzm8523 commented on src/main/java/calculator/domain/Calculator.java
> +        return ret;
Stream의 세계는 정말 복잡미묘하네요..

2022-12-28 12:20 UTC, ekzm8523 commented on src/main/java/calculator/domain/Calculator.java
> +    }
사실 Int가 아닌 input이 왔을 때의 모든 예외처리들(숫자가 아닌 문자들)을 한 번에 묶어서 `RuntimeException`으로 보내는 제 코드부채입니다..
그런데 제 생각에 음수인지, 숫자가 아닌 다른 글자가 들어온건 아닌지 확인하는 validate 및 Exception은 여기가 아니고 위에서 제안드린 `Interpreter` 혹은 데이터 모델에서 하는 게 좋겠다는 생각이 드는데 어떻게 생각하시나요?

2022-12-28 12:56 UTC, ekzm8523 reviewed
@wade-lim 리뷰주신 부분은 내일 호로록 적용해볼게요 😄
세밀한 리뷰 감사합니다 ( _ _ )

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/calculator/domain/Delimiters.java
> +    }
이 부분은 위에서 제안해주신 데이터 모델을 분리하면 immutable로 관리가 가능할 것 같습니다 👏

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/calculator/domain/Prompt.java
> +    private Matcher getMatcher() {
위에서 제안해주신대로 `getCustomDelimiterMatcher()`는 어떤가요?

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/calculator/domain/Prompt.java
> +        delimiters.add(matcher.group(1));
데이터 모델로 분리 후 그 안에서 validation을 하는 방식으로 변경하겠습니다~

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/calculator/domain/Prompt.java
> +    }
변수명이 명확하지 않네요 !! `Matcher` 에서 반환되는 기본 변수명을 사용하다보니 놓친 것 같아요. 심플하게 delimeter 로 변경하겠습니다. (이와중에 private 옆에 공백 두개.. 🥲)

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/calculator/domain/Prompt.java
> +    }
현재 Calculator에서 호출하기 때문에 public으로 되어있는데 이 부분도 데이터 모델을 분리한다면 사라질 메서드일 것 같아요!!

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/racing/Main.java
> +        gameView.gameFinish();
그 부분도 고민되던 부분이였는데 좋은 것 같아요!!

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/racing/domain/Cars.java
> +        return status;
오 요것도 완전 꿀팁이네요 !! 감사합니다. ( _ _ )

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/racing/domain/Game.java
> +    }
문자열 파싱을 바깥(GameView)에서 해주고 List<String> 형태의 인풋을 받는 생성자를 하나 만들어주는게 좋겠네요!
그러면 `initialize` 메서드도 필요 없고 `gameFinish`, `gamePlay` 메서드를 private으로 가져갈 수 있겠어요!!

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/racing/domain/Game.java
> +    }
앗 사실 처음에는 `Car` 리스트를 반환했다가 메서드명만 바꾸지 않은 제 코드 부채.. 회수하겠습니다.. 🫠

2022-12-28 12:56 UTC, ekzm8523 commented on src/main/java/racing/domain/Game.java
> +    }
1번의 경우 name, position만 갖는 DTO를 만들면 되기 때문에 쉬울 것 같긴 한데 어려운 길로 가보고 싶은 모험가 심리가 또 도지네요 ㅎㅎ.. 프록시 객체를 한 번 만들어 보겠습니다 🫠

2022-12-29 02:33 UTC, wade-lim commented on src/main/java/calculator/domain/Prompt.java
> +public class Prompt {
좋습니다 👍 
두 번째 보다는 첫 번째 방법이 좀 더 객체지향적으로 보이네요~

2022-12-29 02:35 UTC, wade-lim commented on src/main/java/calculator/domain/Prompt.java
> +    private Matcher getMatcher() {
좋습니다~

2022-12-29 02:41 UTC, wade-lim commented on src/main/java/calculator/domain/Calculator.java
> +    }
그렇다면 `RuntimeException` 보다는 해당 의도에 맞는 Exception 클래스를 사용하거나, 그런 클래스가 없다면 RuntimeException 을 상속하는 커스텀 Exception 을 하나 만들어서 사용하는게 좋아 보입니다.

```Java
public class UserInputException extends RuntimeException {
  ...
}
```

validation 을 외부에서 하는 것도 좋아보이네요 :)
단지 그렇게 되면 `Calculator` 역할이 엄청 적어질거 같긴 하네요 😄

2022-12-30 00:46 UTC, ekzm8523 commented
@wade-lim  안녕하세요 웨이드 !! 
계산기는 리뷰해주신 부분 전부 반영했어요!! (거의 새로운 코드 수준..🎇) 
레이싱게임같은 경우는 현재 두 가지가 남았는데요
- Car 프록시 객체를 이용해 immutable화
- GameView와 Game의 기능 분리

위의 두 가지는 2단계인 리팩토링에서 컨트롤러를 추가하면서 반영할 수 있을 것 같아요!!
리뷰반영 확인해주시면 감사하겠습니다 😄

그리고 성능보다는 가독성에 우선을 두어 최대한 스트림을 사용하려고 노력했어요.
성능을 많이 포기한 것 같기는 한데 그래도 스트림과 친해지는데 많은 도움이 된 것 같기는 합니다.!!

2022-12-30 02:30 UTC, wade-lim approved these changes
고생하셨습니다!!

레이싱카 쪽은 말씀해주신 대로 2단계 때 고민해주셔도 될 것 같고, 계산기는 엄청 깔끔해진 것 같네요 :)

2022-12-30 02:30 UTC, wade-lim commented on src/main/java/calculator/domain/Number.java
> +        }
[의견]
Number 클래스 따로 만들어서 음수 체크하는거 좋네요~

2022-12-30 02:30 UTC, wade-lim commented on src/main/java/calculator/domain/Numbers.java
> +    List<Number> numbers;
[확인]
`private final` 이어도 될 것 같습니다~

2022-12-30 02:30 UTC, wade-lim commented on src/main/java/calculator/domain/Command.java
> +                .forEach(ch -> validateCharNumber(delimiterSet, ch));
[의견]
forEach 쪽에서 `(char) ch` 로 형변환 해줘도 될거 같아요~

2022-12-30 02:31 UTC, merged