2단계 미션 제출합니다.
next-step/java-racingcar-kakao pull request #50
Opened 2024-03-30 16:40 UTC by kjk7212

기존 코드 자체가 domain이 view를 의존하지 않게 구현되어 있었기 때문에,
피드백 내용을 반영하는 것을 중점적으로 진행했습니다.

그런데 궁금한 부분이 하나 생겼습니다.
interface와 다형성을 이용하여 숫자 생성 방식을 제어하게 코드를 작성하긴 했습니다만,
딱 테스트 만을 위해 사용되는 inteface와 class라는 생각을 지울 수 없었습니다.
실제 업무에서도 비즈니스 로직에는 필요가 없지만 테스트하는데 필요한 코드를 작성하는 경우가 있나요??

2024-03-31 15:18 UTC, liquidjoo requested changes
안녕하세요 성국님 :)
이전 단계의 피드백, 2단계 미션 구현 잘해주셨어요 👍 
몇가지 코멘트 남겼습니다~ 확인하고 다시 요청 주세요 🙇

2024-03-31 15:18 UTC, liquidjoo commented on src/main/java/calculator/Calculator.java
> +			return ZERO;
피드백 반영 👍

2024-03-31 15:18 UTC, liquidjoo commented on src/main/java/calculator/Parser.java
> +	private static final Pattern CUSTOM_DELIMITER_PATTERN = Pattern.compile("//(.)\n(.*)");
상수화 👍

2024-03-31 15:18 UTC, liquidjoo commented on src/main/java/racingcar/controller/RacingController.java
> +		GameResults gameResult = gameStart();
피드백 반영 좋습니다 👍

2024-03-31 15:18 UTC, liquidjoo commented on src/test/java/racingcar/RacingGameTest.java
> +		racingGame = new RacingGame(names, 3, new CustomNumberGenerator(4));
https://github.com/next-step/java-racingcar-kakao/pull/50#issue-2216574127

에 대한 답변을 드리면!
`RacingGame` 은 인터페이스를 주입 받고 있습니다~ 
구현할 구현 메서드가 적을 경우에는 익명함수로 사용하고 있습니다 :) 익명함수로 작성해 보면 좋을 것 같아요 ~
> 저는 실제 업무에서 테스트를 위한 구현체는 만들지 않습니다! 대신 테스트를 위한 FakeObject 정도는 만들 것 같아요 or 앞에서 언급한 인터페이스 구현체를 익명함수로 구현해서 사용하곤 합니다!

2024-03-31 15:18 UTC, liquidjoo commented on src/main/java/racingcar/model/CustomNumberGenerator.java
> +public class CustomNumberGenerator implements NumberGenerator{
익명함수를 사용해 본다면 해당 구현체는 필요 없어질 것 같네요 !

2024-03-31 15:18 UTC, liquidjoo commented on src/main/java/racingcar/model/Car.java
>  public class Car {
놓쳤던 것이 있었네요 😭 
기본 생성자는 실질적인 로직에서 사용하지 않는다면 접근 제어자를 통해 제어해보면 어떨까요?

2024-03-31 21:59 UTC, kjk7212 commented on src/main/java/racingcar/model/Car.java
>  public class Car {
테스트 외에서는 쓰지 않던 것을 발견하여 그냥 지웠습니다!

2024-03-31 22:01 UTC, kjk7212 commented on src/test/java/racingcar/RacingGameTest.java
> +		racingGame = new RacingGame(names, 3, new CustomNumberGenerator(4));
람다 구문을 찾아보고 적용해보니 확실히 코드도 짧아지고 구현체도 필요 없어져서 좋은 것 같습니다 😙

2024-03-31 22:02 UTC, kjk7212 commented on src/main/java/racingcar/model/CustomNumberGenerator.java
> +public class CustomNumberGenerator implements NumberGenerator{
람다 구문을 적용하고 제거했습니다!

2024-04-01 14:06 UTC, liquidjoo approved these changes
안녕하세요 성국님 :)
2단계 피드백 반영 잘해주셨어요 💯 
저와 함께 했던 리뷰가 도움이 되었길 빌며
남아있는 미션들도 화이팅 입니다
수고하셨습니다 🙇

2024-04-01 14:06 UTC, liquidjoo commented on src/main/java/racingcar/model/Car.java
> +	private final String name;
final 활용 👍

2024-04-01 14:06 UTC, liquidjoo commented on src/test/java/racingcar/CarTest.java
> +		car = new Car("test");
피드백 반영 좋습니다 👍

2024-04-01 14:06 UTC, liquidjoo commented on src/test/java/racingcar/RacingGameTest.java
> +		racingGame = new RacingGame(names, 3, () -> 4);
람다 할용 👍

2024-04-01 14:06 UTC, merged