2단계 미션 제출합니다.
next-step/java-racingcar-kakao pull request #53
Opened 2024-03-31 15:17 UTC by junohpark221

### 개선점
- 지난 1단계 미션을 merge하면서 받았던 마이너한 피드백들을 이번 2단계를 구현하는 과정에 추가하여 함께 리팩토링을 진행했습니다. (#24)
- 기존에 MVC 패턴을 감안하며 설계하였기에, Controller와 View를 조금 더 명확하게 분리하는 방향으로 2단계를 구현해보았습니다.

### 궁금한 점
- 현재 사용자의 input으로 받은 데이터를 검증하기 위하여, Validator라는 객체를 구현해놓은 상황입니다 (e.g. 글자 수, 데이터 타입 등 검증). 이 때, validate의 과정을 객체 별 메소드로 나누어서, 객체 생성 시 validate를 하는 방향으로 구현하는 것이 객체 지향에 어울리는 방향인지, 혹은 지금과 같은 Validator 객체를 사용하는 것이 더욱 어울리는 방향인지 여쭤보고 싶습니다.

2024-04-01 09:28 UTC, sah3122 requested changes
2단계 미션 구현 잘해주셨습니다 👍 
몇가지 코멘트 남겨두었는데 확인 부탁드려요 🙏

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/calculator/Delimiter.java
> +    private static final Pattern pattern = Pattern.compile("//(.)\\n*");
피드백 반영 👍 
일반적으로 static 변수는 클래스 최상단에 위치하곤 합니다 😄

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/calculator/Delimiter.java
> -            return expression.substring(5);
남겨드린 코멘트의 의도는 `m.group(2)`와 같이 matcher 를 활용하여 expression을 뽑아낼수 있다고 생각하였습니다 😄

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/racing/Application.java
> +        CarView carView = new CarView();
입력값을 받는 View와 출력하는 View를 나누어 보는건 어떨까요 ?

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/racing/Application.java
> +        carView.printWinner(carController.getCarList());
이번 미션을 진행하며 UI Layer와 Domain Layer간의 의존을 제거 해보세요 😄 
현재 CarView라는 UI Layer까지 Domain 객체가 전달되는 구조 입니다. 
Domain 객체가 UI Layer까지 전달되면 어떤 문제가 생길지, 레이어 간의 격리를 위해 어떤 작업이 필요한지 고민해보시길 바랍니다.

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/racing/controller/CarController.java
>      private List<Map<String, Integer>> gameLogs;
Map 자료구조를 사용하는 대신 값 전달을 위한 객체를 정의해보는건 어떨까요 ?

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/racing/domain/CarList.java
>      private final Map<String, Car> carHashMap;
List<Car> 대신 Map을 사용한 이유가 궁금합니다 😄 

개인적으로 변수명에 자료구조를 나타내는것을 지양합니다. 
자료구조가 변경되는 상황에서 변수명까지 변경하는것 보단, 복수형으로 선언하여 조금더 유연하게 사용할수 있다고 생각해요.

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/racing/domain/CarList.java
> +        this.carHashMap = createCarHashMap(createCarList(carNames));
생성자가 늘어남에 따라 도메인 요구사항을 지킬수 있는 비즈니스 로직이 분산될수 있습니다. 
이러한 경우 하나의 생성자를 주 생성자로 선언하고, 부 생성자는 주 생성자를 호출하는 구조로 비즈니스 로직을 모아보는건 어떨까요 ?

2024-04-01 09:28 UTC, sah3122 commented on src/main/java/racing/domain/CarList.java
> +    private List<Car> createCarList(String carNames) {
Validator에 대해서 질문 주셨는데, 개인적인 생각은 아래와 같습니다. 
Validator 객체를 분리 시켜 유효성 검증에 대한 책임을 모아주신 부분은 좋다고 생각합니다. 
앞선 미션의 코멘트(https://github.com/next-step/java-racingcar-kakao/pull/24/files#r1542182984) 의 의도는 외부에서 유효성 검사를 하는것과 도메인 객체가 유효성 검사 로직을 가지고 있는것에 대해 어떤 차이점이 있는지 알려드리기 위해 남겨드렸습니다. 
코멘트 남겨주신것 처럼 Validator 객체가 유효성 검사를 하여 현재 코드로는 요구사항을 만족하는 객체만 생성되는것처럼 보입니다. 
하지만 테스트 코드에서 이름이 5글자가 초과하는 객체를 생성시 정상적으로 생성되는것을 확인할수 있어요. 
이처럼 도메인 클래스는 어느 한 부분에서만 사용되는것이 아니라, 시스템 전반적인 곳에서 사용될수 있다는점을 항상 염두하고, 매번 완전한 도메인 객체가 생성될수 있도록 구현해야한다고 생각해요. 

정리하지면 Validator 클래스를 너무 믿지 않고, 도메인 클래스에도 유효성 검사 로직이 포함되어야 한다고 생각합니다 😄 
유효성 검사 로직은 적은것 보단 많은것이 좋다고 생각해요 🙏

2024-04-01 15:17 UTC, junohpark221 commented on src/main/java/racing/domain/CarList.java
>      private final Map<String, Car> carHashMap;
좋은 의견 감사합니다! 우선 Map을 사용한 이유로는, carName을 기반으로 Car 객체에 쉽게 접근 가능한 것이 테스트를 하거나 구현을 하는 것에 있어서 용이하다고 판단했기 때문입니다! 따라서 carName을 key로 하고 Car 객체를 value로 하는 Map으로 구현했습니다.

이어서 말씀주신 것 처럼 자료구조 형태로 변수 명 및 클래스 명을 명명한 부분이 있는 것으로 보여, Cars로 명명하도록 수정했습니다!

2024-04-01 15:23 UTC, junohpark221 commented on src/main/java/racing/Application.java
> +        CarView carView = new CarView();
좋은 의견 감사합니다! View를 나누는 방향으로 수정 완료 했습니다 :)

2024-04-01 15:29 UTC, junohpark221 commented on src/main/java/racing/Application.java
> +        carView.printWinner(carController.getCarList());
좋은 피드백 감사합니다! 말씀 하신 내용을 생각해보니, 아무래도 View에 Domain 객체가 직접 전달될 경우에는 도메인 비즈니스 기능이 노출될 위험이 생길 수 있고 의존성으로 인하여 분리가 제대로 이루어지지 않는다는 문제점이 발생할 수 있다는 생각이 들었습니다! 따라서 List 형태의 winner 변수를 View에 전달하도록 수정했습니다!

2024-04-01 15:41 UTC, junohpark221 commented on src/main/java/racing/controller/CarController.java
>      private List<Map<String, Integer>> gameLogs;
피드백 감사합니다! 말씀 듣고 고민해 본 결과, GameLog 객체와 GameLogs 객체를 정의하여 게임 로그를 관리하는 것이 좋다고 판단되어, 해당 내용을 추가하고 수정했습니다 :)

2024-04-01 15:43 UTC, junohpark221 commented on src/main/java/racing/domain/CarList.java
> +        this.carHashMap = createCarHashMap(createCarList(carNames));
주 생성자를 통해 모아보는 방향으로 수정해보았습니다! this(); 내에서 클래스 내의 메소드를 호출하기 위하여 static 메소드로 수정하는 것과 함께 리팩토링 진행해보았습니다 :)

2024-04-01 15:46 UTC, junohpark221 commented on src/main/java/racing/domain/CarList.java
> +    private List<Car> createCarList(String carNames) {
좋은 답변 정말 감사합니다! 말씀 주신 것 처럼 앞단에서  Validator를 통해 유효성 검증이 진행되더라도, 도메인 클래스 내에서 유효성 검사 절차를 가지는 것은 필요한 것 같네요 :) 앞으로도 validate를 어떻게 진행하고 구현할지 생각해보는 경험이 된 것 같습니다!

말씀 주신 것 처럼 해당 부분을 수정해서 반영해놓았습니다!

2024-04-01 15:52 UTC, junohpark221 commented on src/main/java/calculator/Delimiter.java
> -            return expression.substring(5);
해당 부분을 참고하여 수정해보고자 시도를 계속했는데 잘 안 되는 것 같습니다..! 다른 분들의 정규 표현식을 참고하여 "//(.)\n(.*)" 형태의 정규표현식을 활용하여 grouping을 하고자 했는데요, string 값의 매칭도 일어나지 않을 뿐더러 grouping 역시 제대로 되지 않는 것 같아요..!

해당 부분을 수정해보려고 하다고 계속 실패하여, 우선 코멘트를 남기고 다시 푸시 합니다!

2024-04-03 13:45 UTC, sah3122 approved these changes
피드백 반영 잘해주셨습니다 👍 
이번 미션은 여기서 마무리 짓도록 할게요.
남아있는 과정들도 끝까지 완주하세요 😄

2024-04-03 13:45 UTC, sah3122 commented on src/main/java/racing/domain/Cars.java
>      }
피드백 반영 잘해주셨습니다 👍

2024-04-03 13:45 UTC, sah3122 commented on src/main/java/racing/domain/GameLog.java
> +public class GameLog {
값 전달을 위한 객체 선언 👍

2024-04-03 13:45 UTC, sah3122 commented on src/main/java/racing/view/CarOutputView.java
> +    public static void printWinner(List<Car> winners) {
List<Car> 대신 List<String>과 같이 전달 받을수 있으면 의존성을 완전히 제거해볼수 있을것 같아요 😄

2024-04-03 13:45 UTC, merged