[orion.jeong] Step2. 자동차 경주 MVC 패턴 적용
next-step/java-racingcar-kakao pull request #59
Opened 2022-12-28 15:16 UTC by knight7024

잘 부탁드립니다.

2022-12-29 07:15 UTC, KakaoOceanWorld requested changes
전체적으로 엄청 빠르고 훌륭하게 하셔서 크게 피드백 드릴게없네요
그래도 몇가지 코멘트 드렷으니 확인부탁드릴게용 같이 이야기해봐요

2022-12-29 07:15 UTC, KakaoOceanWorld commented on src/main/java/racing_car/model/Cars.java
> +    public boolean equals(Object o) {
@knight7024 cars 의 equals는 override 하신 이유가 있으실까요?

2022-12-29 07:15 UTC, KakaoOceanWorld commented on src/main/java/racing_car/model/Cars.java
> +        this.cars = cars == null ? new ArrayList<>() : new ArrayList<>(cars);
@knight7024 할당과 비교를 동시에 하는게 그렇게 가독성이 좋은지는 잘모르겠습니다

2022-12-29 07:15 UTC, KakaoOceanWorld commented on src/main/java/racing_car/model/Game.java
>              moveCar(i);
@knight7024 전체적으로 너무 빠르게 잘 구현해주셔서 한가지 제안드립니다
만약 자동차를 움직이는 전략이 랜덤말고 다른 방법이 추가된다면?

저희 파트에서도 실제 프로덕션 코드에선 랜덤한 난수를 사용하고 개발 페이즈에서는 특정 값을 고정해서 쓰는 경우가 있는데요,
이럴때 [전략패턴](https://velog.io/@kyle/%EB%94%94%EC%9E%90%EC%9D%B8-%ED%8C%A8%ED%84%B4-%EC%A0%84%EB%9E%B5%ED%8C%A8%ED%84%B4%EC%9D%B4%EB%9E%80) 을 사용하는것도 한 가지 방법입니다 한번 적용해봐도 좋을것같아요 (강요하는건 절대 아닙니다)

2022-12-29 07:15 UTC, KakaoOceanWorld commented on src/main/java/racing_car/model/Game.java
> +    private static final int END_THRESHOLD = 10;
@knight7024 START_THRESHOLD / END_THRESHOLD
보다 더 좋은 이름 없을까요 
움직이기 위한 최소값?, 최대 생성 난수?    MIN 과 MAX 라는 단어가 들어가면 좋을것같아요

2022-12-29 07:15 UTC, KakaoOceanWorld commented on src/main/java/racing_car/model/Car.java
>          return "-".repeat(this.distance);
@knight7024 이건 view 에서 차의 distance만 안다면 만들수있어서 view에게 책임을 넘겨도 좋을것같다는 생각이 드네요

2022-12-29 07:15 UTC, KakaoOceanWorld commented on src/test/java/racing_car/RacingCarTest.java
> +public class RacingCarTest {
@knight7024 얘도 calculator 처럼 단위테스트 하는것들은 RacerTest, CarTest등으로 나눠도 좋겟네요

2022-12-29 08:20 UTC, knight7024 commented on src/main/java/racing_car/model/Cars.java
> +    public boolean equals(Object o) {
테스트코드에서 assertEquals를 통해 같은 자동차들을 가지고 있는지 확인하려고 했습니다.

2022-12-29 11:28 UTC, knight7024 commented on src/main/java/calculator/model/Validator.java
> +public class Validator {
생성자를 private으로 선언하고 내부에서 `throw new UnsupportedOperationException();`를 구현하라는 말씀으로 이해했는데 맞을까요? 만약 그렇다면 throw는 단순히 동료들이 알기 쉽게 하는 용도인걸까요?

2022-12-29 13:20 UTC, knight7024 commented on src/main/java/racing_car/model/Game.java
>              moveCar(i);
전략패턴을 통해 자동차가 움직일 수 있는지 여부를 확인하도록 적용하였습니다.

다만 해당 여부를 확인하는 책임은 `Game` 객체가 가져야 한다고 생각해서 생성자를 통해 전략 인터페이스를 받도록 만들었습니다.
제가 구현한 방법이 적절한지 피드백 주시면 감사하겠습니다!!

2022-12-31 06:21 UTC, KakaoOceanWorld commented on src/main/java/calculator/model/Validator.java
> +public class Validator {
@knight7024 이해하신게 맞습니다 
그냥 private 로만 선언해도 그만이긴 하지만 명시적으로 throw를 하게하면 Validator 내부에서도 얘는 인스턴스를 따로 만들면 안되겠구나 더 상기할 수 있겠죠

2022-12-31 06:35 UTC, KakaoOceanWorld commented on src/main/java/racing_car/model/Game.java
>              moveCar(i);
@knight7024 적절히 구현해주셨습니다 말씀하신대로 Car는 그냥 움직이면 되고 Game 객체가 move 전략을 알아야겠죠

2022-12-31 06:38 UTC, KakaoOceanWorld commented
@knight7024 고생하셨습니다. 피드백도 빠르게 반영해주셔서 감사드립니다 다음미션에서 뵙겠습니다 :)

2022-12-31 06:38 UTC, merged