Java Racing Car PR from choijxwxn/step2 to next-step/choijxwxn
next-step/java-racingcar-kakao pull request #68
Opened 2022-12-29 07:17 UTC by CHOIJXWXN

안녕하세요 요한
채널개발2셀에 입사하게 된 제리입니다!

제 엉성한 코드에 꼼꼼하게 코드 리뷰 작성해주셔서 정말 감사합니다 :)
요한이 말씀해주신 부분을 유의해서 리팩토링을 해보았습니다!
빨리 리뷰를 받아보고 싶어서 문자열 계산기 부분은 제쳐두고 자동차 경주 코드만 해보았어요
혹시 제가 잘못 이해한 부분이 있거나, 아직도 고쳐지지 않은 부분이 있으면 코멘트 부탁드립니다

앞으로도 잘 부탁드려요 💪💪

2022-12-30 02:15 UTC, leeyohan93 requested changes
제리 안녕하세요~
연말이다보니 리뷰가 늦었네요 😢 
이전에 드렸던 코멘트들에 대한 피드백 잘 반영해주셨네요 💯 💯 
소소한 코멘트를 남겨 놓았으니 확인 부탁드려요
궁금한점이나, 어려운점 있다면 코멘트나 톡으로 편하게 연락주세요 :)

2022-12-30 02:15 UTC, leeyohan93 commented on src/main/java/racing/domain/Car.java
> +    }
carEvent 메서드는 자동차 객체가 어떤 일을 할지 유추하기 어려운 네이밍인 것 같아요!
좀 더 명확한 메서드 네이밍을 사용해보면 어떨까요?

2022-12-30 02:15 UTC, leeyohan93 commented on src/main/java/racing/domain/Car.java
> +    }
이번 단계 가이드 문서에보면 아래와 같은 요구사항이 있는데요 :)
`핵심 로직을 구현하는 코드와 UI를 담당하는 로직을 구분한다.`

View의 요구사항이 변경되었을 때 View와 관련된 모듈만 변경된다면 좋을 것 같아요.

2022-12-30 02:15 UTC, leeyohan93 commented on src/test/java/racing/CarTest.java
> +public class CarTest {
이전에 작성해주신 테스트보다 훨씬 가독성이 있네요!
테스트도 리팩토링이 꼭 필요합니다! 잘해주셨어요 👍 👍

2022-12-30 02:15 UTC, leeyohan93 commented on src/main/java/racing/domain/Result.java
> +public class Result {
Result 클래스에서는 아무 상태도 캡슐화하고 있지 않은데요. 
저는 개인적으로 이런 유형의 클래스는 메서드를 나누는 역할을 할 뿐, 객체로써의 역할을 하지 못한다고 생각해요!
그렇다면 우승자를 판별하는 메서드가 좀 더 적합한 객체는 어떤 객체일까요?

`엘레강트 오브젝트` 라는 책에 보면 아래와 같은 이야기도 있는데 한번 참고해보시면 좋을 것 같아요 :)
https://jackjeong.tistory.com/m/151
```
최소한 뭔가는 캡슐화하세요
너무 많이 캡슐화하는 방식도 좋지 않지만, 아무것도 캡슐화하지 않는 방식 또한 바람직하지 않습니다.
```

2022-12-30 06:05 UTC, CHOIJXWXN commented on src/main/java/racing/Game.java
> +    static Car[] carList;
코드 컨벤션 중에 메서드가 10 line이 넘어가서는 안 된다는 부분이 있어서
main 함수 안의 내용을 handleNames(), playRacing(), winnerResult()로 분리했습니다.
그러다보니 세 메서드가 같은 carList 객체를 공유하고 있어야 해서 static으로 선언했습니다.
handleNames(), playRacing(), winnerResult()가 각각 carList를 파라미터로 가지고 carList를 반환하는 것이 더 좋은 코드일까요?

2022-12-30 06:42 UTC, leeyohan93 commented on src/main/java/racing/Game.java
> +    static Car[] carList;
static으로 선언하지 않으면 세 메서드가 공유하지 못하는 것일까요? 🤔 

추가적으로 Game 클래스에 대한 제 생각을 남겨볼게요. 참고만해주세요 😄 
Game 클래스를 컨트롤러 클래스라고 정의해주셨는데, 저는 컨트롤러에서는 상태 값을 가지면 안된다고 생각합니다.
만약 자동차 게임을 여러 번 실행한다면, 이전 게임의 정보가 남아있을 수 있지 않을까요? :)

2023-01-02 04:42 UTC, leeyohan93 requested changes
안녕하세요 제리!
피드백도 잘 반영해주습니다! 레이싱카에 이어 문자열 계산기도 리팩토링해주셨네요!
코드에서 많이 고민하신 흔적이 느껴져서 좋았습니다! 💯 💯 
조금 더 개선해보면 좋을 점들에 대해서 코멘트 남겨놓았으니 확인 부탁드려요~
새해 복 많이 받으세요 😄

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/racing/domain/Racing.java
> +public class Racing {
https://github.com/next-step/java-racingcar-kakao/pull/68#discussion_r1059215678

이전에 드렸던 코멘트와 동일하게 Racing 클래스도 아무것도 캡슐화하고 있지 않고 있어요!
Game 클래스는 컨트롤러이지만, 도메인 로직에 깊게 관여하고 있는 부분들이 보이는데, 그 부분들을 Racing의 책임으로 이동해보면 어떨까요?

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/racing/domain/CarList.java
> +public class CarList {
자료구조의 이름을 그대로 클래스나 변수의 이름으로 가져가는 것은 지양해야한다고 생각해요.
만약 요구사항이 바뀌어 List가 아닌 Set으로 바뀌어야한다면 어떨까요?

Cars 와 같이 복수형 네이밍을 사용해보는건 어떨까요?

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/racing/domain/CarList.java
> +    private Car[] cars;
컬렉션 대신 배열을 사용해주시는 이유가 궁금합니다 :)

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/racing/domain/Racing.java
> +        return carList;
일급 컬렉션 객체를 만들어주셨으니, getter를 사용하지 않고 메시지를 전송하는건 어떨까요?

```suggestion
        carList.move(new RandomlyMove())
        return carList;
```

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/racing/domain/RandomlyMove.java
> +    }
전략 패턴 사용 💯 💯 

RandomlyMove 의 생성자에서 번호를 생성하게 되면, RandomlyMove 객체를 반복해서 생성하게 될 것 같은데요. 성능을 최적화 하는 방법은 없을까요?

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/racing/domain/Result.java
> +        return winners;
winners를 사용하지 않더라도 CarList 객체만 있다면 우승자를 구할 수 있을 것 같아요.
우승자를 구하는 책임을 CarList 에게 이전해보는건 어떨까요? :)

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/racing/domain/Car.java
> +            throw new IllegalArgumentException("빈칸은 입력할 수 없습니다.");
구체적인 예외 사용 💯 💯

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/StringCalculator/domain/Delimiter.java
> +    private final static Pattern pattern = Pattern.compile(CUSTOM_DELIMITER_REGEX);
이미 아시겠지만 상수의 네이밍은 대문자가 컨벤션입니다 :)

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/StringCalculator/domain/Summation.java
> +                        return Integer.parseInt(element);
아래 프로그래밍의 요구사항을 지키도록 메서드를 분리해보는건 어떨까요?

`규칙 1: 한 메서드에 오직 한 단계의 들여쓰기(indent)만 한다.`

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/StringCalculator/domain/Summation.java
> +        }
구현해주신 catch 문은 어떤 상활 일 때 동작하게 되나요??
단순한 질문입니다! 😄

2023-01-02 04:42 UTC, leeyohan93 commented on src/main/java/StringCalculator/domain/Summation.java
> +        }
실무에서는 try catch 로 예외를 잡았을 때는 기존 예외를 스택트레이스 확인을 위해 꼭 로그에 남겨주시는게 좋습니다! :)
참고만해주세요 :)

2023-01-02 11:08 UTC, CHOIJXWXN commented on src/main/java/racing/domain/CarList.java
> +    private Car[] cars;
입력 시점부터 끝까지 크기가 고정인 변수라 배열을 사용했습니다. 배열 대신 컬렉션을 사용하면 더 이점인 부분이 있을까요?

2023-01-02 11:44 UTC, CHOIJXWXN commented on src/main/java/StringCalculator/domain/Summation.java
> +                        return Integer.parseInt(element);
해당 부분을 validate 메서드로 분리하려고 하는데 혹시 validate 메서드가 어떠한 값을 반환하는 건 컨벤션에 위반될까요?
```
private int validatePositive(String element) {
    int number = Integer.parseInt(element);
    if (number < 0) {
        throw new IllegalArgumentException("양수를 입력해주세요);
    }
    return number;
}
```
이런 식으로요
이런 방식이 좋지 않다면
```
private int validatePositive(String element) {
    if (Integer.parseInt(element) < 0) {
        throw new IllegalArgumentException("양수를 입력해주세요);
    }
}
```
로 정의한 후에 다시 Integer.parseInt(element)값을 계산하여 사용하는 건 괜찮을까요?

2023-01-02 11:48 UTC, CHOIJXWXN commented on src/main/java/StringCalculator/domain/Summation.java
> +        }
예를 들어, 커스텀 구분자를 `*`를 사용하고싶을 때 delimiterRegex가 "*"가 되어버리는데
그러면 단순 문자가 아닌 정규식에서 사용되는 특수한 의미를 가지는 기호로 인식되어서 예외가 발생했습니다.
그래서 split을 할 때 예외가 생기면 일단 앞에 escape를 위한 \\를 추가해보는 처리를 해보았습니다!

2023-01-02 12:45 UTC, CHOIJXWXN commented on src/main/java/racing/domain/Result.java
> +        return winners;
이런 도메인 책임 관련해서 아직 헷갈리는 부분이 많습니다.
책임 분배 기준이 주요 메서드 개수에 따른 걸까요?
단순히 메서드 개수도 고려할 수 있겠지만, 가지고 있는 필드 내에서 해결할 수 있느냐 없느냐로 판단할 때도 있는 것 같아요.
혹은 더 중요한 다른 고려사항들도 있을까요?

제가 한 책임 분리가 과도한 것인지 부족한 것인지 판단할 수 있는 기준이 있는지 알고 싶고, 이와 관련해서 참고해보면 좋을 만한 키워드가 있다면 알고 싶습니다.

2023-01-03 01:43 UTC, leeyohan93 commented on src/main/java/racing/domain/CarList.java
> +    private Car[] cars;
제네릭과 관련된 부분이나 컬렉션에서 제공해주는 편리한 메서드들이 있다는 점이 있습니다.
자세한 내용은 아래 링크의 이펙티브 자바 내용을 참고해주세요 :)

https://madplay.github.io/post/prefer-lists-to-arrays

2023-01-03 01:57 UTC, leeyohan93 commented on src/main/java/racing/domain/Result.java
> +        return winners;
저는 책임을 분배할 때는 메서드의 개수를 기준으로 두지는 않는 것 같습니다.
물론 메서드가 많아지면, 책임을 분리해야하는 신호로 생각이 될 수는 있습니다.

`오브젝트` 책을 보면 아래와 같은 문장이 있는데요. 
> 자율적인 객체를 만드는 가장 기본적인 방법은 책임을 수행하는데 필요한 정보를 가장 잘 알고 있는 전문가에 그 책임을 할당하는 것이다.

자동차 경주의 현재 `우승자를 구한다` 라는 책임으로 생각해보면 어떨까요?
우승자를 구하는 방법은 `자동차들` 중 가장 많이 이동한 자동차를 찾는 것이기 때문에
`자동차들` 이라는 객체에 `우승자를 구한다`라는 책임을 분배해주는 것도 괜찮아 보이네요.

아래 링크는 오브젝트에서 위 문장이 있던 챕터의 내용을 요약인데, 도움이 되었으면 좋겠어요 :)
https://incheol-jung.gitbook.io/docs/study/object/2020-03-10-object-chap3

2023-01-03 02:01 UTC, leeyohan93 commented on src/main/java/StringCalculator/domain/Summation.java
> +                        return Integer.parseInt(element);
이야기해주신 것 처럼 validate 메서드가 어떠한 값을 반환하는 건 일반적으로 기대하지 못한 행동이라고 생각합니다! 👍 
Integer.parseInt(element)를 수행한 뒤에 검증하는건 어떨까요?

```java
private int validatePositive(Int element) {
    if (element < 0) {
        throw new IllegalArgumentException("양수를 입력해주세요);
    }
}
```

2023-01-03 02:03 UTC, leeyohan93 commented on src/main/java/StringCalculator/domain/Summation.java
> +        }
케이스 공유 감사합니다 👍 👍 
이런 특수한 케이스가 있다면 try catch 로 처리하기 보다는 별도의 케이스로 분리해서 처리하는건 어떨까요?
예상치 못한 다른 예외가 발생했을 때 지금의 로직은 정상적으로 동작할 수 없을 가능성도 있어 보이네요! 🤔

2023-01-03 02:08 UTC, leeyohan93 approved these changes
전반적으로 개선된 부분들이 좋았습니다! 고생하셨어요 💯 💯 
많이 고민하고 끝까지 도전해주시는 모습에 저도 리뷰하는데 힘이났습니다 👍 👍
고민하시던 부분은 코멘트로 남겨두었으니 확인 부탁드려요 :)
다음 미션도 화이팅입니다.🔥
감사합니다.

2023-01-03 02:08 UTC, merged