미션 제출합니다.
next-step/java-racingcar-kakao pull request #7
Opened 2024-03-26 06:59 UTC by riroan

2024-03-26 16:17 UTC, liquidjoo requested changes
안녕하세요 명기님
이번 미션 리뷰어를 맡은 김성주 입니다 :)
미션 잘 구현해주셨어요 👍 
몇 가지 코멘트 남겼는데요~ 확인하고 다시 요청주세요 🙇

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/calculator/Calculator.java
> +    public int calculate(List<Integer> numberList) {
상태 값이 없고 메서드만 존재하게 된다면 해당 객체는 불완전한 객체가 될 것 같은데요
불완전 객체에 대해 찾아보고 상태 값을 추가하여 완전한 객체로 만들어 보면 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/calculator/Delimiter.java
> +    }
테스트 용도로만 사용된 객체라면 제거해보는 것이 어떨까요?
> 매개변수를 통한 테스트를 진행할 때 생성자를 활용해 보면 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/calculator/Delimiter.java
> +    private String checkCustomDelimiter(String expression) {
check 라는 이름은 boolean type 을 반환하거나 예외 처리를 할 것 같은 네이밍인 것 같아요 :)
적절하게 변경해보면 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/calculator/Delimiter.java
> +        Matcher m = Pattern.compile("//(.)\\n*").matcher(expression);
`Pattern.compile("//(.)\\n*")` 에 대한 객체의 생성 비용을 줄여 볼까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/calculator/Delimiter.java
> +public class Delimiter {
테스트 코드가 있으면 좋을 것 같네요 :)

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/controller/CarController.java
> +public class CarController {
MVC 구조에 대해서는 다음 단계에서 리뷰를 더 자세히 드리겠습니다 :)

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/controller/CarController.java
> +        CarList carList = new CarList(createCarList(carNames));
자바 네이밍의 관습 중에 컬렉션보다는 복수를 사용하는 것이 일반적입니다
왜 컬렉션 명을 사용하지 않을까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/controller/CarController.java
> +    }
비즈니스 로직과 View 를 분리하면 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/controller/CarController.java
> +    private List<Car> createCarList(String carNames) {
해당 메서드에 많은 책임이 있는 것 같은데요 :)
역할을 나누어 적절하게 책임을 이동시켜 보면 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/domain/Car.java
> +    }
void 타입도 좋은 방법 중 하나지만, 반환 값을 통해서 테스트 코드를 직관적으로 만들어 보면 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/domain/CarList.java
> +import racing.generator.RandomNumberGenerator;
사용하지 않고 있는 것들은 제거 해주는 것이 좋을 것 같아요 :)

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/domain/CarList.java
> +    Map<String, Car> carHashMap;
상태값으로는 Map 을 받고 있는데 List 로 표현되는 점이 조금 어색하네요:)
컬렉션 네이밍 보다 좀 더 명확한 네이밍을 만들어 보는 것이 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/domain/CarList.java
> +    }
비즈니스 로직을 수행 후 바로 화면을 보여주는 것이 아니라 모든 비즈니스 로직을 수행 후 화면에 노출시켜 볼까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/domain/CarList.java
> +    }
비즈니스 로직에서는 사용하지 않고 테스트에서만 사용하는 것 같은데요 :)
의미가 있는 메서드 일까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/domain/CarList.java
> +    }
별도의 역할로 나누어 보아도 좋을 것 같아요
어떻게 나누어 보면 될까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/generator/RandomNumberGenerator.java
> +        this.random = new Random();
Random 생성 비용을 어떻게 줄여볼 수 있을까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/generator/TrueNumberGenerator.java
> +public class TrueNumberGenerator implements NumberGenerator {
테스트를 위한 구현체라면 익명함수를 사용해보는 것이 어떨까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/main/java/racing/view/CarView.java
> +    }
자동차 경주에 대한 비즈니스 로직을 완료한 후에 출력을 한다면 어떻게 해야할까요?

2024-03-26 16:17 UTC, liquidjoo commented on src/test/java/calculator/SplitterTest.java
> +        Assertions.assertThat(numberList.get(2)).isEqualTo(3);
assertAll 을 활용해보는 것 좋을 것 같네요 :)
assertAll 과 assertThat 의 차이점도 알고 있으면 더욱 좋습니다

2024-03-27 05:42 UTC, riroan commented on src/main/java/calculator/Delimiter.java
> +        Matcher m = Pattern.compile("//(.)\\n*").matcher(expression);
미리 compile 시켜놓고 메소드에서는 matcher만 사용하면 효율적이겠군요! 👍

2024-03-27 05:50 UTC, riroan commented on src/main/java/calculator/Delimiter.java
> +    }
생성자로 옮기겠습니다!

2024-03-27 05:53 UTC, riroan commented on src/main/java/racing/domain/Car.java
> +    }
boolean을 통해 이동했는지 여부를 반환하면 직관적이겠네요!

2024-03-27 06:08 UTC, riroan commented on src/main/java/calculator/Delimiter.java
> +public class Delimiter {
실수로 테스트코드를 빠트렸네요 😞

2024-03-27 06:11 UTC, riroan commented on src/main/java/racing/domain/CarList.java
> +    }
혹시 이 리뷰가 사용자가 5턴을 입력했다면 5턴이 모두 끝난 후 출력하라는 뜻인가요?

2024-03-27 06:25 UTC, riroan commented on src/test/java/calculator/SplitterTest.java
> +        Assertions.assertThat(numberList.get(2)).isEqualTo(3);
assertThat은 25번라인 테스트가 실패하면 26~28 테스트를 실행하지 않아 결과를 알 수 없는데 assertAll을 사용하면 알 수 있네요!

2024-03-27 06:35 UTC, riroan commented on src/main/java/racing/view/CarView.java
> +    }
> 비즈니스 로직을 수행 후 바로 화면을 보여주는 것이 아니라 모든 비즈니스 로직을 수행 후 화면에 노출시켜 볼까요?

이 리뷰랑 같은 의미인가요??

2024-03-27 07:30 UTC, riroan commented on src/main/java/racing/controller/CarController.java
> +    }
이 코멘트는 무슨 의미인지 모르겠습니다. 😢 

> 혹시 이 리뷰가 사용자가 5턴을 입력했다면 5턴이 모두 끝난 후 한번에 출력하라는 뜻인가요?

이 질문이 맞다면 비즈니스로직 모두 수행하고 뷰를 수행하는 형식으로 분리할 수 있을 것 같습니다!

2024-03-27 07:49 UTC, riroan commented on src/main/java/racing/domain/CarList.java
> +    }
getWinner가 getMaxPosition을 의존해서 분리하라는 코멘트로 이해해서 각 메소드의 역할을 명확히 했습니다.

2024-03-27 07:54 UTC, riroan commented on src/main/java/racing/generator/RandomNumberGenerator.java
> +        this.random = new Random();
지금은 RandomNumberGenerator를 생성할 때마다 Random객체를 만들기 때문에 외부에서 주입받으면 Random객체를 한 번만 생성할 수 있겠네요!

2024-03-27 08:27 UTC, riroan commented on src/main/java/calculator/Calculator.java
> +    public int calculate(List<Integer> numberList) {
계산기 객체에 상태를 넣을 요소가 없고 그렇다고 controller에 이 메소드를 넣기엔 controller의 책임이 많아진다고 느꼈는데 이럴 때는 어떻게 처리해야 하나요?

2024-03-27 08:28 UTC, riroan commented on src/main/java/racing/domain/CarList.java
> +    }
테스트코드에서 private인 carHashMap에 접근할 수 없어서 만든 메서드로 기억합니다. 그래서 테스트 결과를 확인하기 위해 만든 메서드입니다!

2024-03-27 08:36 UTC, riroan commented on src/main/java/racing/controller/CarController.java
> +    private List<Car> createCarList(String carNames) {
split하고 리스트를 생성하는 책임을 가지고 있는 것 같아 split하는 기능을 밖으로 뺐습니다 :)

2024-03-27 08:40 UTC, riroan commented on src/main/java/racing/controller/CarController.java
> +        CarList carList = new CarList(createCarList(carNames));
컬렉션 이름을 사용한 변수의 타입이 다른 컬렉션으로 변경됐을 때 동일하게 이름이 바껴야 하기 때문이네요!
예를들어 List<Car> carList -> Set<Car> carList로 바뀐다면 사용중인 모든 carList라는 변수명을 carSet으로 바꿔야 하는 문제점이 있었습니다.

2024-03-27 08:58 UTC, riroan commented
코멘트 반영했습니다!

2024-03-28 05:50 UTC, closed without merging