[jaws.bar] 자동차 경주 2단계
next-step/java-racingcar-kakao pull request #79
Opened 2022-12-29 09:59 UTC by park0503

## 구현 내용
- 1단계에서 구현했던 내용을 MVC 구조를 참고해 리팩토링 했습니다.
- Console 및 NumberGenerator의 경우 메인 게임 엔진과는 거리가 있다고 생각해 인터페이스를 이용해 메인 로직과 분리시켰습니다.
## 궁금점
- Car 내의 getPosition의 경우 RacingGameTest에서 race 메소드가 정상 동작 하는지를 확인하기 위해서만 사용됩니다. 즉 Test만을 위해서 구현한 메소드로 볼 수 있습니다. 목적과 수단이 뒤바뀐 느낌이라 이러한 경우를 없애고 싶었지만 마땅한 방법이 떠오르지 않아 냅둔 상태입니다. 보통 이런 일이 현업에서도 발생을 하나요? 발생한다면 카야는 어떻게 대처하시는 편인지 궁금합니다.

2022-12-29 17:24 UTC, gayeon1025 requested changes

2022-12-29 17:24 UTC, gayeon1025 commented on src/main/java/racingcar/engine/domain/Car.java
> +    }
차의 위치를 출력할 때 RacingView에서 `cars.forEach((car) -> console.printOutput(car.toString()));` 와 같이 출력하고 있는데요. `car.toString()` 라면 차의 어떤 속성을 출력하려는지 명확하게 드러나지 않아 toString 구현까지 확인해봐야하는 아쉬움이 있습니다. 차의 위치를 출력하는 것이므로 `console.printOutput(car.getPosition))`과 같이 표현하면 차의 위치를 출력함이 명시적으로 드러날 것 같습니다. 

getPosition을 사용하게 되면 현재 고민점이 없어지겠지만ㅋㅋㅋ 별개로 말씀을 드립니다!
실제로 서비스를 구현할 때 저희도 많이 고민하고 사실 저도 어제 팀원들과 동일한 문제로 논의했습니다😂
테스트 코드만을 위한 메서드나 필드 작성은 최대한 지양하는 게 좋습니다. 테스트코드만을 위한 코드를 작성하지 않기 위함 꼼수(?)들을 최대한 활용합니다. 아래는 실제로 저희 코드에서 활용한 경우입니다!
1. 로직에서는 필드를 직접 set할 필요가 없어서 setter를 두지 않았는데 테스트코드(tc)에서 mock 객체의 값을 set해야하는 경우 reflection을 활용하여 값을 set합니다.
2. private 메서드만 테스트 하고 싶다고 해당 메서드를 public으로 바꾸는 대신, Junit의 ReflectionTestUtils를 활용합니다.

2022-12-29 17:24 UTC, gayeon1025 commented on src/main/java/racingcar/engine/domain/RacingGame.java
> +            max = car.renewWinners(max, winners);
메서드를 호출하는 클라이언트는 본인이 넘긴 파라미터가 내부에서 조작될 것이라고 기대하지 않습니다. 따라서 어떤 부작용을 낳을지 알 수 없기 때문에 파라미터로 넘긴 값을 조작하는 것은 지양하는 것이 좋을 것 같습니다! 
다른 방식으로 우승자를 가리도록 구현해주시면 좋을 것 같습니다

2022-12-29 17:24 UTC, gayeon1025 commented on src/main/java/racingcar/engine/view/InputParser.java
>          }
InputParser 클래스는 들어온 인풋을 파싱하는 용도일 뿐 로직이 섞이지 않는 것이 좋을 것 같습니다. 
자동차 경주에서 최소 2대 이상의 자동차를 받았는지 확인은 파서가 아닌 상위에서 확인하는 건 어떨까요?

2022-12-29 17:24 UTC, gayeon1025 commented on src/main/java/racingcar/engine/view/InputParser.java
>          } catch (NumberFormatException e) {
NumberFormatException을 던지고 있는 곳은 어디일까요? 불필요하다면 삭제 부탁드립니다!

2022-12-29 17:31 UTC, gayeon1025 requested changes

2022-12-29 17:31 UTC, gayeon1025 commented on src/main/java/racingcar/App.java
> +        RacingView racingView = new RacingView(console);
RacingGame을 생성할 때 console을 받아서 `this.racingView = new RacingView(console);` 와 같이하면 외부에서 숨겨져서 좋지 않을까요? 죠스의 생각이 궁금합니다~

2022-12-29 17:36 UTC, gayeon1025 commented
@park0503 설계가 가장 머리 아픈데 리팩토링도 금방하시다니 아주 멋져요 죠스🦈
궁금한 점과 요청사항이 있습니다~
1. Console과 NumberGenerator를 작성한 건 디자인패턴을 의도하신걸까요??
2. 패키지 구조를 다시 한 번 고민 부탁드립니다! mvc 패턴을 적용했음이 패키지 구조에 잘 드러났으면 좋겠어요!

코드리뷰는 제가 일방적으로 커멘트를 드리는 게 아니라 서로의 생각을 공유하는(사실 저도 배우는...) 자리이니 항상 저의 생각이 정답이 아니라는 점 말씀드립니다!! 죠스의 코드는 죠스가 제일 많이 고민하셨을테니 오히려 죠스의 생각이 맞을 때가 더 많을 수도 있어욬ㅋㅋ 저번처럼 적극적인 답변은 언제든 환영입니다!

2022-12-30 03:07 UTC, park0503 commented on src/main/java/racingcar/engine/view/InputParser.java
>          }
입력값 검증을 최대한 몰아서 하려고 위치시킨건데, 말씀하신대로 비즈니스 로직과 연관된 검증은 domain 쪽에서 해결하는 것이 맞아 보이네요. 감사합니다!

2022-12-30 03:07 UTC, park0503 commented on src/main/java/racingcar/engine/view/InputParser.java
>          } catch (NumberFormatException e) {
Integer.parseInt 메소드에서 숫자가 아닌 형태의 입력이 들어오면 생기는 예외라 위와 같이 처리했습니다!

2022-12-30 03:08 UTC, park0503 commented on src/main/java/racingcar/App.java
> +        RacingView racingView = new RacingView(console);
확실히 외부에서 주입 받을 필요가 있는 Console과 다르게 RacingView는 따로 주입 받을 필요는 없어 보이네요!
수정하는게 좋아 보입니다. 좋은 의견 감사합니다!

2022-12-30 03:41 UTC, park0503 commented on src/main/java/racingcar/engine/domain/Car.java
> +    }
어디선가 해당 객체의 정보를 단순 문자열로 return하는 경우에는 toString 메소드를 적극 활용하라는 글을 본 적이 있어 다음과 같이 진행했는데, 사실 조금 아리송하긴 했습니다. Car의 현재 위치를 요구사항에 맞춰 특정 포맷의 string으로 리턴하는 것을 객체의 정보를 단순 문자열로 리턴하는 것이라 볼 수 있는지 헷갈렸기 때문인데요, 말씀처럼 역할을 좀 더 명시적으로 드러낼 수 있는 메소드를 만드는 것이 더 좋아 보입니다.

실제로도 현업에서 나오는 고민이군요 ㅋㅋㅋ reflection을 활용해서 문제를 해결할 방법을 찾아보겠습니다. 감사합니다!

2022-12-30 03:43 UTC, park0503 commented
@gayeon1025 
1. 디자인 패턴을 염두에 두고 작성한 것은 아니고 입/출력 및 랜덤 수 생성기는 로직과 떨어져 있기도 하고 언제든지 교체될 수 있다고 생각해 다음과 같이 구현했습니다. 다만 구현하고 보니 전략 패턴과 유사한 느낌이 드네요.
2. 흠 일단은 어떻게 수정해야할 지 바로 떠오르지는 않는데 한 번 더 고민해 보겠습니다. 피드백 감사합니다!

2022-12-30 05:52 UTC, gayeon1025 commented
@park0503 
전략패턴을 염두해두고 일부러 그렇게 설계하신 줄 알았는뎈ㅋㅋㅋㅋ [언제든지 교체될 수 있다고 생각해] 요렇게 설계하셨다니 방향이 좋았던 거 같아요! 실제로도 전략패턴은 비즈니스 로직이 쉽게 바뀔 수 있도록 해주는 패턴이라서 딱 적재적소에 쓰신 것 같습니다!👍
요거는 꼭 필수사항도 아니고 저의 개인적인 취향인데 전략패턴의 인터페이스에는 XXXStrategy(ex. ConsoleStrategy) 등을 붙여주고는 합니다! 다른 동료들이 봤을 때 한 눈에 전략패턴을 차용했음을 알 수 있게 해주는 것 같아서 저는 이렇게 명명하고는 합니다(그냥 tmi 입니닿ㅎㅎ 개선 사항은 아닙니다!)

패키지구조를 설정하는 데 있어서 완벽한 정답은 없지만 관례적인 구조를 사용하면 쉽게 동료들과 통용할 수 있는 장점이 있는 것 같아요. [참고링크](https://primetime.tistory.com/entry/Spring-MVC-%EA%B5%AC%EC%A1%B0)도 한 번 드려봅니다!

2022-12-30 06:14 UTC, gayeon1025 requested changes
테스트코드 리뷰를 미쳐 드리지 못해 다시 리뷰 드려요!

2022-12-30 06:14 UTC, gayeon1025 commented on src/test/java/racingcar/RacingGameTest.java
> +        Assertions.assertThat(racingGame.isEnd()).isTrue();
tc 메서드 1당 1개의 내용만 테스트하는 걸 추천드려요! 해당 메서드에서는 
1. count만큼 게임을 다 끝내기 전에는 isEnd가 false인지 확인
2. 게임이 모두 종료된 후에는 isEnd가 true인지 확인
총 2가지를 확인하고 있다고 생각합니다. 

@Nested와 @DisplayName을 사용해보신 적이 있을까요?
@Nested로 테스트를 적절히 묶는다면 비슷한 조건에서 테스트를 진행하는 친구들의 코드를 조금이나마 줄일 수 있어 효과적입니다! @DisplayName을 함께 사용하면 읽기에도 훨씬 편한 코드가 될 수 있습니다!

테스트 결과도 아래처럼 깔끔하게 확인 가능합니다
![image](https://user-images.githubusercontent.com/33685994/210040262-b6ad6ee3-5c13-4ed1-aec4-929eb23a9b5d.png)

참고 1: https://rutgo-letsgo.tistory.com/319
참고 2: https://bcp0109.tistory.com/297

2022-12-30 06:14 UTC, gayeon1025 commented on src/test/java/racingcar/RacingGameTest.java
> +        });
NumberGenerator가 함수형 인터페이스이기 때문에 더 축약하여 간편하게 작성할 수 있을 것 같습니다!

2023-01-02 02:57 UTC, park0503 commented
@gayeon1025 우승자 판별 로직, 값 검증, 테스트 코드 관련해 피드백 반영 및 리팩토링을 진행했습니다!

2023-01-02 06:51 UTC, gayeon1025 approved these changes
👍 피드백 반영하시느라 수고 많으셨습니다
* 테스트코드가 깔끔하고 가독성이 좋은 것 같아요
* 패키지 구조도 mvc가 잘 드러나게 구성해주신 것 같네요

이번 과제에서는 레이어에 대해서는 고민하지 않았는데 뒷 과제에서는 레이어도 고민을 해야할 것 같아요! 그 전에 미리 읽어보는 것도 좋을 것 같아 [링크](https://umbum.dev/1066) 함께 첨부드립니다. 수고 많으셨습니다.

2023-01-02 06:51 UTC, merged