[noah.u] 문자열 덧셈 계산기 + 자동차 경주 2단계
next-step/java-racingcar-kakao pull request #89
Opened 2022-12-30 02:44 UTC by qsc7342

안녕하세요, 오웬~!
1차 피드백에서 굉장히 상세하게 피드백해주셔서 감사합니다!
바쁘시겠지만 2차 피드백도 요청드려봅니다!!
*****
### 1차 피드백 반영 및 테스트 추가
1차 피드백을 반영하고, 개인적으로 부족하다 생각한 부분을 개선했습니다.
2차 주요 주제가 MVC 패턴으로 변경하는 것으로 보이는데, 1차 때 이미 진행했던 부분이라서 그대로 유지했어요.
<img width="330" alt="image" src="https://user-images.githubusercontent.com/29935107/209931182-54912429-b1d5-4431-8cad-cb02caa0319a.png">

그래서 피드백 부분을 개선하고 개인적으로는 테스트 부분이 조금 아쉬워 그 부분을 개선하는 방향으로 진행했습니다!
개선점들은 README의 step2 부분에서 확인할 수 있습니다! 커밋 단위는 리드미 한줄을 기준으로 하고자했어요.
 PR이 너무 길어질 것 같아, 1차 피드백 개선 관련 내용은 [여기](https://ginger-deer-ecb.notion.site/Week1-ad886cf01f50486aa5ba3746368a84c5)에 간략히 담아보았습니다.
 
 개인적으로는 `Comparable 인터페이스를 사용`하여 우승자 찾는 방법을 변경한 점이 가장 기억에 남네요!!
 
 ***** 
### 랜덤넘버 테스트
 랜덤넘버와 관련한 테스트를 1차 PR에서는 disable 상태로 두었었는데요~
 이 부분은 함수를 오버로딩해서 테스트를 진행하는 방법을 선택했습니다.
 ``` java
     public boolean isMovable(int input) {
        return input >= THRESHOLD;
    }

    public boolean isMovable() {
        return isMovable(generateRandomNumber(RANDOM_BOUND));
    }
  ```
*****
### 테스트를 위한 Getter
 Delimiters 테스트를 작성할 때, 인스턴스 변수를 가져와야 하는 상황이 발생했었습니다!
 그런데 프로덕션 코드에서는 사용하지 않는 Getter를 테스트를 위해 추가하는게 맞는가하는 생각이 들었습니다.
 
 스택 오버플로우에 [유닛 테스트를 위해 게터 세터를 추가하는 것이 옳은가?](https://stackoverflow.com/questions/22722930/adding-getters-and-setters-for-the-sake-of-unit-testing)와 관련된 질문글이 있더라구요.
 
 답변에 리플렉션을 통해 테스트 코드에서 인스턴스 변수를 가져오는 방법을 발견하여 적용해보았습니다!
 
``` java
    @SuppressWarnings("unchecked")
    private List<Delimiter> getDelimiters() throws NoSuchFieldException, IllegalAccessException {
        Field field = delimiters.getClass()
                        .getDeclaredField("delimiters");
        field.setAccessible(true);
        return (List<Delimiter>) field.get(delimiters);
    }
```

 항상 감사드립니다.
 이번에도 잘 부탁드립니다~!!

2023-01-02 06:09 UTC, owen-q commented on README.md
> +### 리팩토링 진행 ( Step2 )
오 미션1때의 PR과 비교하면 엄청나게 상세한 TODO 리스트네요 🧐

2023-01-02 06:51 UTC, owen-q requested changes
안녕하세요 노아~! 

2단계 미션 진행 하시느라 고생 많으셨어요 
피드백 반영도 상세하게 해주시고, 미션 진행하시면서 공부하시게 된것들을 요약해주셔서 덕분에 이것저것 배웠습니다 👍

PR에서 질문 주셨던 내용에 대해서 답변 드렸구요 
피드백 드린 부분 확인후에 다시 PR 요청 부탁드릴게요!

2023-01-02 06:51 UTC, owen-q commented on README.md
> +### 리팩토링 진행 ( Step2 )
오 미션1때의 PR과 비교하면 엄청나게 상세한 TODO 리스트네요 🧐

2023-01-02 06:51 UTC, owen-q commented on src/main/java/calculator/domain/calculator/delimiter/Delimiter.java
> +        if (delimiter.length() != 1) {
매직넘버는 상수로 빼내주시려는 습관이 생기면 좋을거같아요~!

2023-01-02 06:51 UTC, owen-q commented on src/main/java/calculator/domain/calculator/prompt/Input.java
>      String input;
클래스 내부 변수는 특별한 이유가 없는한 private으로 생성해두면 좋을거 같습니다~!

2023-01-02 06:51 UTC, owen-q commented on src/main/java/calculator/util/RegexUtils.java
> +public class RegexUtils {
XXXUtils로 코드를 분리해두신 노력이 보여요~
XXXUtils는 말 그대로 여러 클래스에서 재사용이 가능하고, 명확한 기능으로 분류 가능할때에 보통 사용한다고 생각해요 
RegexUtils 클래스는 그런 측면에서 유틸 클래스로 제공할만한 기능까지는 아닌거 같아서 오버엔지니어링의 느낌이 조금은 듭니다! 

다만 기능에 대해서 유틸로 분리하려고 고민하신건 좋습니다 👏

2023-01-02 06:51 UTC, owen-q commented on src/main/java/racing/domain/car/Car.java
> +    private int position;
차의 이름을 String name;으로 두지 않고 
Name이라는 클래스로 wrapping하였고, 그 안에서 차의 이름에 관련된 로직을 구현해주셨는데요 

마찬가지로 int position에 대해서도 위치 관련된 로직을 모아볼수 있지 않을까요~?

2023-01-02 06:51 UTC, owen-q commented on src/main/java/racing/strategy/strategy/AlwaysMovableStrategy.java
> +public class AlwaysMovableStrategy implements MovableStrategy {
테스트를 위한 코드로 보여요 
실제로 비즈니스에서는 사용되지 않은 코드라면 삭제해도 괜찮을거 같아요~!

2023-01-02 06:51 UTC, owen-q commented on src/test/java/racing/domain/car/CarTest.java
> +                    .movableStrategy(new AlwaysMovableStrategy())
AlwaysMovableStrategy 을 삭제하면 좋을거 같다는 의견을 드렸었는데요,
그러면 여기 테스트 코드에서는 movable에 대해서 어떻게 테스트가 가능할까요?

2023-01-02 06:51 UTC, owen-q commented on src/test/java/racing/domain/car/CarTest.java
> +        int expected = car.getPosition() + 1;
기대하는 값인 expected가 테스트에 의존적인거 같아요 
이 TC는 차를 1번 움직이고, 그에 대한 기대값이 1이기 때문에 

move() TC에 expected의 값을 받아와도 좋을거같아요, (ParameterizedTest를 활용하여) 

혹은 차에 대해서 위치를 비교하는 기능이기 때문에 아래와 같이 isEqualPosition 을 활용할수도 있을거같아요 
```suggestion

// 실제 작성해주신 코드랑은 맞지 않지만 예시를 위해서 축약했습니다 
assertThat(car.isEqualPosition(new Car(expected)));
```

2023-01-02 06:51 UTC, owen-q commented on src/main/java/racing/strategy/interfaces/MovableStrategy.java
> +public interface MovableStrategy {
지난번에 질문 주셨었던 랜덤 로직에 대한 테스트를 잘 처리해주셨네요 👏 
고민 더 해보시라고 미션1단계에서는 직접 답을 안드렸었는데 잘 작성해주셨습니다

2023-01-02 06:51 UTC, owen-q commented on src/test/java/calculator/delimiter/DelimitersTest.java
> +    private List<Delimiter> getDelimiters() throws NoSuchFieldException, IllegalAccessException {
PR에서 질문 주셨었던 Getter 관련된 부분이네요~

우선 비즈니스 로직과 테스트 코드 모두에서 getter와 setter를 가급적 사용 안하는게 제일 좋을거 같습니다 
getter, setter를 외부에 열어줌에 따라 오류가 발생할 가능성이 늘어난다고 생각해요 
그래서 TC를 위해서 비즈니스로직에서는 사용되지 않는 getter를 추가하는건 지양해야 한다는게 제 의견입니다 

TC를 위해 추가된 getter는 본 비즈니스 로직에 안좋은 영향을 줄수 있지만 
리플렉션의 경우 비즈니스 로직과는 분리되어 테스트 코드상에서 테스트 케이스를 검증 할 수 있는 방법으로 보여요 

이 방법에 대해서는 많이 고민하거나 접해본 방법은 아니라서 자세히 얘기 드리긴 어려울거 같아요 
하지만 테스트 케이스에 대해서 더 고민을 해주시고, 구현하는 객체에 대해서도 주어진 역할이 명확한지 등의 방법으로 코드를 보완해가는게 더 좋을거 같다는 의견입니다! 

cc @kykapple

2023-01-02 06:51 UTC, owen-q commented on src/test/java/racing/domain/car/CarTest.java
> +    public void isNotEqualPosition() {
getter 를 사용하지 않고 비즈니스 로직인 isEqualPosition을 통해서 검증하고자 하는바를 깔끔하게 처리해주셨네요 👏

2023-01-03 00:40 UTC, qsc7342 commented on README.md
> +### 리팩토링 진행 ( Step2 )
감사합니다 오웬!
원래 한줄한줄 작성해나가며 추가해나갔어야했는데.. 첫번째 PR에서는 그런 부분을 놓쳤군요.

2023-01-03 00:41 UTC, qsc7342 commented on src/main/java/calculator/domain/calculator/delimiter/Delimiter.java
> +        if (delimiter.length() != 1) {
변경하였습니다!
자꾸 원시값으로 넣으려고하는데, 지금 진행중인 로또에서는 최대한 상수로 빼내려고 하고있습니다.

감사합니다!

2023-01-03 00:41 UTC, qsc7342 commented on src/main/java/calculator/domain/calculator/prompt/Input.java
>      String input;
오 접근제어자를 안붙여두었군요..
감사합니다!

2023-01-03 00:42 UTC, qsc7342 commented on src/main/java/racing/domain/car/Car.java
> +    private int position;
포지션도 마찬가지로 원시값 포장을 진행해보았습니다!
Car의 Comparable을 구현한 비교함수의 경우 아래와 같은 형태로 변경하는 등 변경이 이루어졌습니다.
```java
    @Override
    public int compareTo(@NotNull Car car) {
        return position.compare(car.position);
    }
```

2023-01-03 00:45 UTC, qsc7342 commented on src/test/java/racing/domain/car/CarTest.java
> +                    .movableStrategy(new AlwaysMovableStrategy())
위에서 말씀해주신 것처럼 실제로 비즈니에서 사용되지 않는 테스트용 구현체들을 모두 삭제하였습니다.
위 테스트의 경우 객체를 생성할 때 함수를 오버라이딩하는  방식으로 해결하여 랜덤이 아닌 특정 값을 리턴하도록 변경하여 해결할 수 
있었습니다!
``` java
        Car car1 = new Car.Builder("car")
                .position(before)
                .movableStrategy(new MovableStrategy() {
                    @Override
                    public boolean isMovable() {
                        return false;
                    }
                })
                .build();
```

2023-01-03 00:47 UTC, qsc7342 commented on src/test/java/racing/domain/car/CarTest.java
> +        int expected = car.getPosition() + 1;
오 그렇군요, 이렇게하면 테스트에서 사용되었던 `getPosition()`도  없어질 수 있을 듯 합니다.
@CsvSource를 사용하여 ParameterizedTest를 진행하도록 변경하였습니다.

이제 getter는 출력을 위해 사용했던 것 외에는 사용되지 않는군요.
감사합니다!

2023-01-03 00:51 UTC, qsc7342 commented on src/main/java/racing/strategy/interfaces/MovableStrategy.java
> +public interface MovableStrategy {
감사합니다 오웬!
구현체를 추가로 구현하는 이슈가 위에서 있었지만요.:sweat:
그것도 해결하고 나니 괜찮은 방법이였던 듯 합니다!

2023-01-03 00:58 UTC, qsc7342 commented on src/main/java/calculator/util/RegexUtils.java
> +public class RegexUtils {
오 그렇군요!
사실 [여기](https://commons.apache.org/proper/commons-lang/javadocs/api-3.9/org/apache/commons/lang3/RegExUtils.html)를 보고 Utils 클래스로 분리를 해도 괜찮을 것 같다는 생각이 들었거든요.
지금 같은 경우에는 기능이 그리 많지 않아서 분리까지 하는 것은 오버엔지니어링 일 수도 있겠군요:open_mouth:

감사합니다!

2023-01-03 01:37 UTC, qsc7342 commented on src/test/java/calculator/delimiter/DelimitersTest.java
> +    private List<Delimiter> getDelimiters() throws NoSuchFieldException, IllegalAccessException {
오 그렇군요.
여태까지는 setter는 조금 위험할 수 있다고 생각했지만, getter는 괜찮지 않을까라고 생각을 가지고 있었거든요.
이번에 getter를 사용하지 않고 객체에 메시지를 보내는 방식으로 구현을 하는 방법을 많이 배운 것 같아. 앞으로 그런 방식으로 구현하도록
노력해야할 것 같습니다. 감사합니다!

2023-01-03 01:37 UTC, qsc7342 commented on src/test/java/racing/domain/car/CarTest.java
> +    public void isNotEqualPosition() {
감사합니다 오웬~!

2023-01-03 01:42 UTC, qsc7342 commented
안녕하세요 오웬!
코드 리뷰 감사드립니다!
피드백 주셨던 부분들을 반영해보았는데요. 상세 내용은 코멘트를 확인해주시면 감사하겠습니다!

수정한 부분은
1. 매직 넘버 상수 처리
2. 인스턴스 변수 private 추가
3. Position 값을 담는 객체 생성
4. 불필요한 인터페이스 구현체를 제거하고 Movable 테스트 진행입니다!

2023-01-04 02:02 UTC, owen-q approved these changes
피드백 반영 감사합니다 노아 👏 
미션 진행하느라 고생 많으셨어요 
이번 미션은 머지 진행하겠습니다, 로또 미션도 화이팅입니다~!

2023-01-04 02:02 UTC, merged